Repository Sifchain/sifnode, pull requests merged in 2020-11, with the labels that each got.

#163 feature/readme-testnet-peers
  readme.md
Labels: Ready for Review

#44 Feature/clp
  Makefile
  api/openapi/Dockerfile
  api/openapi/Makefile
  api/openapi/clp_get.yml
  api/openapi/clp_post.yml
  app/app.go
  cmd/ebrelayer/txs/parser.go
  cmd/ebrelayer/txs/parser_test.go
  cmd/ebrelayer/txs/test_common.go
  cmd/sifnoded/main.go
  config.yml
  go.mod
  go.sum
  scripts/peggy-basic-demo.sh
  scripts/peggy-clp-demo.sh
  ui/core/tsconfig.json
  x/clp/README.md
  x/clp/abci.go
  x/clp/alias.go
  x/clp/client/cli/flags.go
  x/clp/client/cli/query.go
  x/clp/client/cli/tx.go
  x/clp/client/rest/query.go
  x/clp/client/rest/rest.go
  x/clp/client/rest/tx.go
  x/clp/clp_suite_test.go
  x/clp/genesis.go
  x/clp/handler.go
  x/clp/handler_test.go
  x/clp/keeper/keeper.go
  x/clp/keeper/keeper_test.go
  x/clp/keeper/params.go
  x/clp/keeper/querier.go
  x/clp/keeper/querier_test.go
  x/clp/keeper/test_common.go
  x/clp/module.go
  x/clp/types/asset.go
  x/clp/types/codec.go
  x/clp/types/errors.go
  x/clp/types/events.go
  x/clp/types/expected_keepers.go
  x/clp/types/genesis.go
  x/clp/types/keys.go
  x/clp/types/keys_test.go
  x/clp/types/msgs.go
  x/clp/types/params.go
  x/clp/types/querier.go
  x/clp/types/types.go
  x/ethbridge/types/ethereum.go
  x/ethbridge/types/test_common.go
Labels: Ready for Review

#132 Persistent Volume setup
  build/Rakefile
  build/helm/sifnode/templates/sifnode-deployment.yaml
  build/helm/sifnode/templates/sifnode-pvc.yaml
  build/helm/sifnode/templates/storageclass.yaml
  build/terraform/providers/aws/main.tf
  build/terraform/providers/aws/variables.tf
  docs/2.DevOps-manual.md
Labels: Ready for testing

#168 feature/welcome-validator
  build/rakelib/genesis.rake
  build/rakelib/helpers.rake
  build/rakelib/validator.rake
Labels: Ready for Review

#173 changed pool formula
  x/clp/handler.go
Labels: Ready for Review

#181 bugfix/sifgen-genesis
  tools/sifgen/common/types/genesis.go
  x/clp/module.go
Labels: Ready for Review

#184 feature/genesis-tokens
  build/rakelib/validator.rake
  go.mod
  go.sum
  tools/sifgen/common/common.go
  tools/sifgen/common/types/genesis.go
  tools/sifgen/genesis/genesis.go
Labels: Ready for Review

#201 [ChainOps] Feature/export-state
  build/rakelib/chain.rake
Labels: Ready for Review

#207 hotfix/compose
  build/scripts/entrypoint.sh
Labels: Ready for Review

#217 [ChainOps] feature/sifgen-token-denom
  build/rakelib/validator.rake
  readme.md
  tools/sifgen/common/types/genesis.go
Labels: Ready for Review

#200 [Peggy] Feature/admin api
  testnet-contracts/.env.example
  testnet-contracts/ADMIN-API.md
  testnet-contracts/Deployment.md
  testnet-contracts/contracts/BridgeBank/BridgeBank.sol
  testnet-contracts/contracts/BridgeBank/CosmosBank.sol
  testnet-contracts/contracts/CosmosBridge.sol
  testnet-contracts/migrations/2_next.js
  testnet-contracts/scripts/setOracleAndBridgeBank.js
  testnet-contracts/scripts/setup_eRowan.js
  testnet-contracts/test/test_bridgeBank.js
  testnet-contracts/test/test_cosmosBridge.js
  testnet-contracts/test/test_end_to_end.js
  testnet-contracts/test/test_oracle.js
Labels: Ready for Review

#203 [Clp] Feature/clp refactor uint
  api/openapi/sifchain-openapi.yml
  go.mod
  go.sum
  simapp/app.go
  x/clp/alias.go
  x/clp/client/cli/tx.go
  x/clp/client/cli/tx_test.go
  x/clp/client/rest/tx.go
  x/clp/handler.go
  x/clp/handler_test.go
  x/clp/test/test_common.go
  x/clp/types/asset.go
  x/clp/types/errors.go
  x/clp/types/keys.go
  x/clp/types/msgs.go
  x/clp/types/msgs_test.go
  x/clp/types/params.go
  x/clp/types/types.go
Labels: Ready for Review

#246 Feature improve relayer error handling
  cmd/ebrelayer/main.go
  cmd/ebrelayer/relayer/ethereum.go
  cmd/ebrelayer/txs/registry.go
  cmd/ebrelayer/txs/relayToEthereum.go
  cmd/ebrelayer/txs/signature.go
Labels: Under Review

#202 [ChainOps] Feature/pr-doc
  .github/workflows/feature.yml
  .github/workflows/merged.yml
  build/rakelib/cluster.rake
  build/rakelib/helpers.rake
  docs/1.Feature Deployments.md
  docs/4.Liquidity Pools Architecture.md
Labels: Ready for Review

#233 Feature/better codecov calcs
  .github/workflows/go.yml
  Makefile
  cmd/ebrelayer/relayer/cosmos.go
  cmd/ebrelayer/relayer/ethereum.go
  cmd/ebrelayer/relayer/network_test.go
  cmd/ebrelayer/txs/registry.go
  cmd/ebrelayer/txs/relayToCosmos.go
  cmd/ebrelayer/txs/relayToEthereum.go
  cmd/ebrelayer/txs/signature_test.go
  codecov.yml
  scripts/cover.sh
  x/ethbridge/handler_test.go
  x/ethbridge/types/test_common.go
Labels: Under Review

#263 remove bin file from repo.
  cmd/ebrelayer/contract/generated/bin/BridgeBank/.gitignore
  cmd/ebrelayer/contract/generated/bin/BridgeBank/BridgeBank.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/BridgeToken.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/Context.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/CosmosBank.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/CosmosBridge.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/ERC20.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/ERC20Burnable.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/ERC20Detailed.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/ERC20Mintable.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/EthereumBank.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/IERC20.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/MinterRole.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/Oracle.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/Roles.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/SafeMath.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/Valset.bin
  cmd/ebrelayer/contract/generated/bin/BridgeBank/WhiteList.bin
  cmd/ebrelayer/contract/generated/bin/BridgeRegistry/.gitignore
  cmd/ebrelayer/contract/generated/bin/BridgeRegistry/BridgeRegistry.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/.gitignore
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/BridgeBank.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/BridgeToken.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/Context.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/CosmosBank.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/CosmosBridge.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/ERC20.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/ERC20Burnable.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/ERC20Detailed.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/ERC20Mintable.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/EthereumBank.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/IERC20.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/MinterRole.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/Oracle.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/Roles.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/SafeMath.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/Valset.bin
  cmd/ebrelayer/contract/generated/bin/CosmosBridge/WhiteList.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/.gitignore
  cmd/ebrelayer/contract/generated/bin/Oracle/BridgeBank.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/BridgeToken.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/Context.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/CosmosBank.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/CosmosBridge.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/ERC20.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/ERC20Burnable.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/ERC20Detailed.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/ERC20Mintable.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/EthereumBank.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/IERC20.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/MinterRole.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/Oracle.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/Roles.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/SafeMath.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/Valset.bin
  cmd/ebrelayer/contract/generated/bin/Oracle/WhiteList.bin
  cmd/ebrelayer/contract/generated/bin/Valset/.gitignore
  cmd/ebrelayer/contract/generated/bin/Valset/SafeMath.bin
  cmd/ebrelayer/contract/generated/bin/Valset/Valset.bin
Labels: Ready for Review

#264 [Peggy] bug/relayer-gas-prices
  build/scripts/entrypoint.sh
  cmd/ebrelayer/main.go
  cmd/ebrelayer/relayer/ethereum.go
Labels: Ready for Review

#245 Update smart contracts and tests to be upgradeable
  smart-contracts/contracts/BridgeBank/BankStorage.sol
  smart-contracts/contracts/BridgeBank/BridgeBank.sol
  smart-contracts/contracts/BridgeBank/CosmosBank.sol
  smart-contracts/contracts/BridgeBank/CosmosBankStorage.sol
  smart-contracts/contracts/BridgeBank/EthereumBank.sol
  smart-contracts/contracts/BridgeBank/EthereumBankStorage.sol
  smart-contracts/contracts/BridgeBank/WhiteList.sol
  smart-contracts/contracts/BridgeBank/WhiteListStorage.sol
  smart-contracts/contracts/BridgeRegistry.sol
  smart-contracts/contracts/CosmosBridge.sol
  smart-contracts/contracts/CosmosBridgeStorage.sol
  smart-contracts/contracts/MockUpgrade/MockCosmsosBridgeUpgrade.sol
  smart-contracts/contracts/Oracle.sol
  smart-contracts/contracts/OracleStorage.sol
  smart-contracts/contracts/Valset.sol
  smart-contracts/contracts/ValsetStorage.sol
  smart-contracts/migrations/2_next.js
  smart-contracts/package.json
  smart-contracts/test/test_bridgeBank.js
  smart-contracts/test/test_cosmosBridge.js
  smart-contracts/test/test_end_to_end.js
  smart-contracts/test/test_oracle.js
  smart-contracts/test/test_upgradeContracts.js
  smart-contracts/test/test_valset.js
Labels: Ready for Review

#260 [ChainOps] EBS CSI plugin and StorageClass in Terraform
  build/helm/sifnode/templates/storageclass.yaml
  build/terraform/providers/aws/main.tf
  build/terraform/providers/aws/variables.tf
Labels: Ready for Review

#266 [Peggy] ebrelayer requires passphrase when witnessing a tx at runtime
  .gitignore
  build/genesis/docker-compose.yml
  build/rakelib/genesis.rake
  build/scripts/entrypoint.sh
  cmd/ebrelayer/main.go
  cmd/ebrelayer/relayer/cosmos.go
  cmd/ebrelayer/relayer/ethereum.go
  cmd/ebrelayer/txs/relayToCosmos.go
  go.mod
  tools/sifgen/common/types/keys.go
  tools/sifgen/network/network.go
  tools/sifgen/network/validator.go
  tools/sifgen/node/node.go
  tools/sifgen/utils/cli.go
Labels: Ready for Review

#274 [ChainOps] feature/rake
  .github/workflows/feature.yml
  .github/workflows/go.yml
  .github/workflows/mainnet.yml
  .github/workflows/merged.yml
  .github/workflows/node.yml
  Rakefile
  build/Rakefile
  build/rakelib/cluster.rake
  build/rakelib/genesis.rake
  build/rakelib/helpers.rake
  go.mod
  go.sum
Labels: Ready for Review

#262 Feature/compose localnet
  build/genesis/docker-compose-ganache.yml
  build/genesis/docker-compose.yml
  docs/4.Running-the-Integration-Test-Suite.md
  scripts/start-integration-env.sh
Labels: Under Review

#261 [ChainOps] Block Explorer helm chart
  build/helm/block-explorer/.gitignore
  build/helm/block-explorer/.helmignore
  build/helm/block-explorer/Chart.yaml
  build/helm/block-explorer/templates/NOTES.txt
  build/helm/block-explorer/templates/_helpers.tpl
  build/helm/block-explorer/templates/configmap-settings.yaml
  build/helm/block-explorer/templates/configmap-url.yaml
  build/helm/block-explorer/templates/deployment.yaml
  build/helm/block-explorer/templates/ingress.yaml
  build/helm/block-explorer/templates/rbac.yaml
  build/helm/block-explorer/templates/service.yaml
  build/helm/block-explorer/templates/serviceaccount.yaml
  build/helm/block-explorer/values.yaml
  build/rakelib/cluster.rake
Labels: Ready for Review

#247 Feature/clp handlers refactor
  config.yml
  scripts/bug267.sh
  scripts/init.sh
  x/clp/alias.go
  x/clp/calculations.go
  x/clp/handler.go
  x/clp/handler_test.go
  x/clp/keeper/executors.go
  x/clp/keeper/keeper.go
  x/clp/keeper/keeper_test.go
  x/clp/test/test_common.go
  x/clp/types/errors.go
  x/clp/types/keys.go
  x/ethbridge/keeper/test_common.go
  x/oracle/keeper/test_common.go
Labels: Ready for Review

#283 [ChainOps] hotfix/change-gas-amount
  deploy/scripts/entrypoint.sh
Labels: Ready for Review

#284 [ChainOps] feature/single-relayer
  deploy/genesis/docker-compose.yml
  deploy/scripts/entrypoint.sh
Labels: Ready for Review

#292 [ChainOps] feature/tee
  .gitignore
  deploy/rake/genesis.rake
  log/.gitkeep
Labels: Ready for Review

#295 [ChainOps] feature/monkey-bars-v6
  readme.md
Labels: Ready for Review

#297 [ChainOps] hotfix/more-gas
  deploy/scripts/entrypoint.sh
Labels: Ready for Review

#301 [ChainOps] feature/supervisor
  deploy/etc/supervisor/conf.d/supervisord.conf
  deploy/genesis/Dockerfile
  deploy/genesis/docker-compose.yml
  deploy/rake/genesis.rake
  deploy/scripts/entrypoint.sh
Labels: Ready for Review

#302 [ChainOps] feature/cors
  deploy/etc/supervisor/conf.d/supervisord.conf
  deploy/genesis/docker-compose.yml
  deploy/helm/sifnode/templates/sifnodecli-deployment.yaml
  deploy/rake/genesis.rake
Labels: Ready for Review

#306 Feature/clp state export
  config.yml
  x/clp/genesis.go
  x/clp/genesis_test.go
  x/clp/keeper/keeper.go
  x/clp/keeper/liquidityprovider.go
  x/clp/keeper/pool.go
  x/clp/module.go
  x/clp/test/test_common.go
  x/clp/types/genesis.go
  x/clp/types/params.go
  x/clp/types/types.go
Labels: Ready for Review

#312 [Frontend] Get vercel working with lerna in the monorepo
  .github/workflows/node.yml
  ui/app/package.json
  ui/core/.gitignore
  ui/core/package-lock.json
  ui/lerna.json
  ui/package.json
  ui/yarn.lock
Labels: Ready for Review

#172 [Clp] Adr doc
  docs/clp-adr.md
Labels: Under Review

#282 Feature/clp supply keeper
  app/app.go
  config.yml
  go.mod
  go.sum
  scripts/clp-asset-List.sh
  simapp/app.go
  x/clp/alias.go
  x/clp/client/cli/query.go
  x/clp/client/rest/query.go
  x/clp/genesis.go
  x/clp/genesis_test.go
  x/clp/handler.go
  x/clp/handler_test.go
  x/clp/keeper/executors.go
  x/clp/keeper/keeper.go
  x/clp/keeper/keeper_test.go
  x/clp/keeper/liquidityprovider.go
  x/clp/keeper/pool.go
  x/clp/keeper/querier.go
  x/clp/module.go
  x/clp/test/test_common.go
  x/clp/types/asset.go
  x/clp/types/expected_keepers.go
  x/clp/types/genesis.go
  x/clp/types/keys.go
  x/clp/types/keys_test.go
  x/clp/types/msgs.go
  x/clp/types/params.go
  x/clp/types/querier.go
  x/clp/types/types.go
Labels: Ready for Review
