Repository Sifchain/sifnode, pull requests merged in 2020-12, with the labels that each got.

#316 [Peggy] Refactor to fix integer overflow
  cmd/ebrelayer/txs/parser.go
  cmd/ebrelayer/txs/parser_test.go
  cmd/ebrelayer/txs/relayToEthereum.go
  cmd/ebrelayer/txs/test_common.go
  cmd/ebrelayer/txs/types.go
  cmd/ebrelayer/types/types.go
  scripts/peggy-e2e-test.py
  x/ethbridge/client/cli/tx.go
  x/ethbridge/client/rest/rest.go
  x/ethbridge/handler.go
  x/ethbridge/handler_test.go
  x/ethbridge/keeper/keeper.go
  x/ethbridge/keeper/keeper_test.go
  x/ethbridge/keeper/querier_test.go
  x/ethbridge/types/claim.go
  x/ethbridge/types/msgs.go
  x/ethbridge/types/test_common.go
Labels: Under Review

#319 [Peggy] Update readme and add artifactor script
  smart-contracts/.openzeppelin/ropsten.json
  smart-contracts/.openzeppelin/unknown-1337.json
  smart-contracts/ADMIN-API.md
  smart-contracts/Artifacts.md
  smart-contracts/Deployment.md
  smart-contracts/build/contracts/BankStorage.json
  smart-contracts/build/contracts/BridgeBank.json
  smart-contracts/build/contracts/BridgeRegistry.json
  smart-contracts/build/contracts/BridgeToken.json
  smart-contracts/build/contracts/Context.json
  smart-contracts/build/contracts/CosmosBank.json
  smart-contracts/build/contracts/CosmosBankStorage.json
  smart-contracts/build/contracts/CosmosBridge.json
  smart-contracts/build/contracts/CosmosBridgeStorage.json
  smart-contracts/build/contracts/CosmosWhiteList.json
  smart-contracts/build/contracts/CosmosWhiteListStorage.json
  smart-contracts/build/contracts/ERC20.json
  smart-contracts/build/contracts/ERC20Burnable.json
  smart-contracts/build/contracts/ERC20Detailed.json
  smart-contracts/build/contracts/ERC20Mintable.json
  smart-contracts/build/contracts/ERC20UNSAFE.json
  smart-contracts/build/contracts/EthereumBank.json
  smart-contracts/build/contracts/EthereumBankStorage.json
  smart-contracts/build/contracts/EthereumWhiteList.json
  smart-contracts/build/contracts/IERC20.json
  smart-contracts/build/contracts/Migrations.json
  smart-contracts/build/contracts/MinterRole.json
  smart-contracts/build/contracts/MockCosmosBridgeUpgrade.json
  smart-contracts/build/contracts/Oracle.json
  smart-contracts/build/contracts/OracleStorage.json
  smart-contracts/build/contracts/Roles.json
  smart-contracts/build/contracts/SafeMath.json
  smart-contracts/build/contracts/Valset.json
  smart-contracts/build/contracts/ValsetStorage.json
  smart-contracts/package-lock.json
  smart-contracts/package.json
  smart-contracts/scripts/saveContracts.js
Labels: Under Review

#307 New Valdiations
  cmd/ebrelayer/txs/parser.go
  cmd/ebrelayer/txs/parser_test.go
  cmd/ebrelayer/txs/test_common.go
  cmd/ebrelayer/txs/types.go
  cmd/ebrelayer/types/types.go
  x/clp/genesis.go
  x/clp/genesis_test.go
  x/clp/handler.go
  x/clp/handler_test.go
  x/clp/keeper/validatorWhiteList_test.go
  x/clp/keeper/validatorWhitelist.go
  x/clp/test/test_common.go
  x/clp/types/genesis.go
  x/clp/types/keys.go
  x/clp/types/msgs.go
  x/clp/types/types.go
  x/ethbridge/client/cli/tx.go
  x/ethbridge/types/claim.go
Labels: Ready for Review

#320 [Testing] Add a github action to run integration tests
  .github/workflows/integrationtest.yml
  deploy/rake/genesis.rake
  deploy/rake/helpers.rake
  docs/4.Running-the-Integration-Test-Suite.md
  scripts/start-integration-env.sh
  test/integration/Dockerfile.testrunner
  test/integration/README.md
  test/integration/add-rowan-to-second-account.sh
  test/integration/add-second-account.sh
  test/integration/docker-compose-ganache.yml
  test/integration/docker-compose-integration.yml
  test/integration/integration-entrypoint.sh
  test/integration/peggy-basic-demo.sh
  test/integration/peggy-basic-test-docker.py
  test/integration/peggy-basic-test.py
  test/integration/peggy-clp-demo.sh
  test/integration/peggy-e2e-test.md
  test/integration/peggy-e2e-test.py
  test/integration/setup-linux-environment-root.sh
  test/integration/setup-linux-environment-user.sh
  test/integration/setup-linux-environment.sh
  test/integration/start-integration-env.sh
  test/integration/stop-integration-env.sh
Labels: Ready for Review

#333 [Peggy] cicd setting for smart contracts
  .github/workflows/smart-contracts.yml
  smart-contracts/README.md
  smart-contracts/package-lock.json
  smart-contracts/package.json
Labels: Ready for Review

#314 [ChainOps] k8s Productionization
  .github/workflows/feature.yml
  cmd/sifgen/main.go
  deploy/helm/block-explorer/Chart.yaml
  deploy/helm/block-explorer/templates/deployment.yaml
  deploy/helm/block-explorer/values.yaml
  deploy/helm/sifnode/Chart.yaml
  deploy/helm/sifnode/templates/NOTES.txt
  deploy/helm/sifnode/templates/ebrelayer-deployment.yaml
  deploy/helm/sifnode/templates/ebrelayer-secret.yaml
  deploy/helm/sifnode/templates/sifnode-configmap.yml
  deploy/helm/sifnode/templates/sifnode-deployment.yaml
  deploy/helm/sifnode/templates/sifnode-pvc.yaml
  deploy/helm/sifnode/templates/sifnode-pvc.yml
  deploy/helm/sifnode/templates/sifnode-role.yml
  deploy/helm/sifnode/templates/sifnode-rolebinding.yml
  deploy/helm/sifnode/templates/sifnode-secret-ghcr.yaml
  deploy/helm/sifnode/templates/sifnode-secret.yml
  deploy/helm/sifnode/templates/sifnode-service.yaml
  deploy/helm/sifnode/templates/sifnodecli-deployment.yaml
  deploy/helm/sifnode/templates/sifnodecli-pvc.yaml
  deploy/helm/sifnode/templates/sifnodecli-service.yaml
  deploy/helm/sifnode/values.yaml
  deploy/helm/swagger-ui/Chart.yaml
  deploy/helm/swagger-ui/values.yaml
  deploy/rake/cluster.rake
  deploy/rake/faucet.rake
  deploy/rake/helpers.rake
  deploy/rake/keys.rake
  deploy/rake/validator.rake
  deploy/terraform/providers/aws/main.tf
  deploy/terraform/template/aws/cluster.tf.tpl
  go.mod
  go.sum
  tools/sifgen/common/common.go
  tools/sifgen/key/key.go
  tools/sifgen/key/key_test.go
  tools/sifgen/node/node.go
  tools/sifgen/sifgen.go
Labels: Under Review

#310 [Frontend] Feature/background events
  ui/app/src/hooks/useCore.ts
  ui/app/src/views/CreatePoolPage.vue
  ui/app/src/views/RemoveLiquidityPage.vue
  ui/app/src/views/SwapPage.vue
  ui/app/src/views/Ui.vue
  ui/core/package.json
  ui/core/src/actions/clp.ts
  ui/core/src/api/MarketService/MarketService.test.ts
  ui/core/src/api/MarketService/index.ts
  ui/core/src/api/SifService/index.ts
  ui/core/src/api/utils/SifClient.ts
  ui/core/src/api/utils/toPool.ts
  ui/core/src/api/utils/x/clp/index.ts
  ui/core/src/entities/Pool.ts
  ui/core/src/hooks/addLiquidityCalculator.test.ts
  ui/core/src/hooks/addLiquidityCalculator.ts
  ui/core/src/hooks/removeLiquidityCalculator.test.ts
  ui/core/src/hooks/removeLiquidityCalculator.ts
  ui/core/src/hooks/swapCalculator.test.ts
  ui/core/src/hooks/swapCalculator.ts
  ui/core/src/store/index.ts
  ui/core/src/store/pools.ts
  ui/yarn.lock
Labels: Ready for Review

#358 [ChainOps] bugfix/relayer-build
  cmd/ebrelayer/Dockerfile
Labels: Ready for Review

#344 Clp/remove sourcechain
  api/openapi/sifchain-openapi.yml
  app/app.go
  cmd/sifgen/main.go
  config.yml
  go.mod
  go.sum
  scripts/bug267.sh
  scripts/clp-asset-List.sh
  scripts/clp.sh
  scripts/init.sh
  test/integration/peggy-clp-demo.sh
  tools/sifgen/common/common.go
  tools/sifgen/common/types/genesis.go
  x/clp/alias.go
  x/clp/client/cli/flags.go
  x/clp/client/cli/tx.go
  x/clp/client/cli/tx_test.go
  x/clp/client/rest/query.go
  x/clp/handler.go
  x/clp/handler_test.go
  x/clp/keeper/executors.go
  x/clp/keeper/keeper_test.go
  x/clp/keeper/liquidityprovider.go
  x/clp/keeper/pool.go
  x/clp/keeper/querier.go
  x/clp/keeper/querier_test.go
  x/clp/test/test_common.go
  x/clp/types/asset.go
  x/clp/types/events.go
  x/clp/types/keys.go
  x/clp/types/msgs.go
  x/clp/types/msgs_test.go
  x/clp/types/querier.go
Labels: Extra attention is needed, Ready for Review

#354 [Peggy] Add openzeppelin folder to gitignore
  smart-contracts/.gitignore
Labels: Ready for Review

#349 Feature/peggy docs
  docs/peggy/Peggy-Arch.md
  docs/peggy/Peggy-Flows.md
  docs/peggy/Peggy-Smart-Contract-Arch.md
  docs/peggy/peggy-images/peggy-flow.png
Labels: documentation, in progress

#364 [Peggy] Better waiting for balances in integration tests
  deploy/rake/genesis.rake
  test/integration/peggy-basic-test-docker.py
  test/integration/peggy-e2e-test.py
  test/integration/test_utilities.py
Labels: Ready for Review

#340 Create peggy tutorial
  docs/peggy tutorial
Labels: Extra attention is needed

#357 [Frontend] Feature/Add getPoolsByLiquidityProvider() and allow env configuration of websocket url
  ui/Dockerfile
  ui/app/src/hooks/useCore.ts
  ui/core/src/actions/clp.ts
  ui/core/src/api/ClpService/ClpService.ts
  ui/core/src/api/utils/SifClient.ts
  ui/core/src/api/utils/toPool.ts
  ui/core/src/api/utils/x/clp/index.test.ts
  ui/core/src/api/utils/x/clp/index.ts
Labels: Ready for Review

#374 Cleanups; docs and scripts folders
  docs/README.md
  docs/chainOps/ChainOps-manual.md
  docs/chainOps/Genesis.md
  docs/clp/Liquidity Pools Architecture.md
  docs/clp/clp-adr.md
  docs/clp/images/SifchainCLPArchitecture/SifchainAddLiquidity.png
  docs/clp/images/SifchainCLPArchitecture/SifchainAppStructure.png
  docs/clp/images/SifchainCLPArchitecture/SifchainCreatePool.png
  docs/clp/images/SifchainCLPArchitecture/SifchainCreateSwapFlow.png
  docs/clp/images/SifchainCLPArchitecture/SifchainDecommissionFlow.png
  docs/clp/images/SifchainCLPArchitecture/SifchainEvent.png
  docs/clp/images/SifchainCLPArchitecture/SifchainMessages.png
  docs/clp/images/SifchainCLPArchitecture/SifchainRemoveLiquidity.png
  docs/clp/images/SifchainCLPArchitecture/SifchainStructs.png
  docs/clp/images/SifchainCLPArchitecture/SifchainSwap.png
  docs/general /Feature Deployments.md
  docs/general /Repo Layout.md
  docs/peggy/Peggy-Flows.md
  docs/peggy/adr-001-peggy-with-sifnode.md
  docs/peggy/images/peggy-flow.png
  docs/testing/.gitkeep
  docs/tutorials/peggy tutorial.md
  scripts/README.md
  scripts/backend-init.sh
  scripts/bugs/bug267.sh
  scripts/cover.sh
  scripts/demos/clp-asset-List.sh
  scripts/demos/clp.sh
  scripts/run.sh
  scripts/setup-e2e.sh
Labels: Ready for Review

#383 [ChainOps] feature/merry-go-round-contracts
  deploy/helm/block-explorer/templates/configmap-scripts.yaml
  deploy/helm/block-explorer/templates/configmap.yaml
  deploy/helm/block-explorer/templates/deployment.yaml
  deploy/helm/block-explorer/values.yaml
  deploy/rake/cluster.rake
  smart-contracts/.gitignore
  smart-contracts/deployments/merry-go-round/BridgeBank.json
  smart-contracts/deployments/merry-go-round/BridgeRegistry.json
  smart-contracts/deployments/merry-go-round/BridgeToken.json
  smart-contracts/deployments/merry-go-round/CosmosBridge.json
  smart-contracts/deployments/merry-go-round/Migrations.json
  smart-contracts/deployments/merry-go-round/Oracle.json
  smart-contracts/deployments/merry-go-round/Valset.json
  smart-contracts/deployments/sandpit/.openzeppelin/ropsten.json
  smart-contracts/deployments/sandpit/.openzeppelin/unknown-1337.json
  smart-contracts/package.json
  smart-contracts/yarn.lock
Labels: Ready for Review

#393 [ChainOps] Set the correct chain ID for the relayer.
  deploy/rake/cluster.rake
Labels: Ready for Review

#397 [ChainOps] feature/k8s-tutorial
  .github/workflows/mainnet.yml
  .github/workflows/release.yml
  .github/workflows/testnet.yml
  docs/tutorials/k8s.md
Labels: Under Review

#399 [ChainOps] bugfix/workflow
  .github/workflows/merged.yml
  .github/workflows/release.yml
Labels: Ready for Review

#396 [Peggy] Test improvments and add test for ceth => eth
  .github/workflows/integrationtest.yml
  test/integration/.env.ciExample
  test/integration/.gitignore
  test/integration/Dockerfile.testrunner
  test/integration/README.md
  test/integration/docker-compose-integration.yml
  test/integration/get_eth_balance.sh
  test/integration/get_sif_balance.sh
  test/integration/monitor-bridgebank.sh
  test/integration/peggy-e2e-test.py
  test/integration/start-integration-env.sh
  test/integration/test_utilities.py
  test/integration/vagrant/.gitignore
  test/integration/vagrant/Makefile
Labels: Ready for Review

#400 [ChainOps] bugfix/tag-name
  .github/workflows/release.yml
Labels: Ready for Review

#407 Tests for block delay
  smart-contracts/package.json
  smart-contracts/scripts/advanceBlock.js
  test/integration/peggy-basic-test-docker.py
  test/integration/peggy-e2e-test.py
  test/integration/start-integration-env.sh
  test/integration/test_utilities.py
  test/integration/vagrant/Makefile
Labels: Ready for Review

#410 [Peggy] Move initial balances to python instead of bash
  test/integration/initial_test_balances.py
  test/integration/peggy-e2e-test.py
  test/integration/start-integration-env.sh
  test/integration/test_utilities.py
Labels: Ready for Review

#338 feature wait 50 blocks to process Ethereum events
  cmd/ebrelayer/relayer/ethereum.go
  cmd/ebrelayer/types/ethEventBuffer.go
  cmd/ebrelayer/types/types.go
  docs/adr-002-ebrelayer-eth-subscribe.md
  test/integration/peggy-basic-demo.sh
  test/integration/peggy-basic-test.py
  test/integration/peggy-e2e-test.py
Labels: in progress

#413 [Bug] ui/chains/ethereum: yarn add truffle (include for local development)
  ui/chains/ethereum/package.json
  ui/chains/ethereum/yarn.lock
Labels: dependencies, frontend

#389 [Frontend] Feature/Notifications
  ui/app/public/favicon.ico
  ui/app/public/favicon.svg
  ui/app/public/index.html
  ui/app/src/App.vue
  ui/app/src/components/Notifications.vue
  ui/app/vue.config.js
  ui/core/src/api/ClpService/ClpService.ts
  ui/core/src/api/EthereumService/index.ts
  ui/core/src/api/EthereumService/utils/getMetamaskProvider.ts
  ui/core/src/api/index.ts
  ui/core/src/api/utils/Notifications.ts
  ui/core/src/entities/Notifications.ts
  ui/core/src/entities/index.ts
  ui/core/src/store/index.ts
  ui/core/src/store/notifications.ts
Labels: frontend

#416 Add support for calling sifnoded add-genesis-validators to integration tests
  test/integration/assemble_data.sh
  test/integration/docker-compose-integration.yml
  test/integration/integration-entrypoint.sh
  test/integration/no_whitelisted_validators.py
  test/integration/peggy-e2e-test.py
  test/integration/setup_sifchain.sh
  test/integration/shell_utilities.sh
  test/integration/sifchain_logs.sh
  test/integration/start-integration-env.sh
  test/integration/test_utilities.py
  test/integration/vagrant/Makefile
Labels: Ready for Review

#414 [ChainOps] CORS Support for the RPC interface.
  deploy/rake/cluster.rake
  deploy/rake/genesis.rake
  deploy/rake/helpers.rake
  tools/sifgen/common/types/config.go
  tools/sifgen/node/node.go
Labels: Ready for Review

#415 [ChainOps] Remove Mnemonic from secrets/ENV.
  deploy/helm/ebrelayer/templates/deployment.yaml
  deploy/helm/ebrelayer/templates/secret.yaml
  deploy/helm/ebrelayer/values.yaml
  deploy/helm/sifnode/templates/sifnode-deployment.yaml
  deploy/helm/sifnode/templates/sifnode-secret.yml
  deploy/helm/sifnode/values.yaml
  deploy/rake/cluster.rake
Labels: Ready for Review

#339 [Core] Consensus Mechanism (block rewards, slashing/jailing, staking, and delegation)
  app/app.go
  app/app_test.go
  app/export.go
  go.mod
  go.sum
  scripts/testGenesis.sh
  test/integration/peggy-basic-test-docker.py
  test/integration/test_utilities.py
  tools/sifgen/common/types/genesis.go
Labels: in progress

#417 [ChainOps] Updated Documentation/Helm updates for ETH
  cmd/sifgen/main.go
  deploy/helm/ethereum/.helmignore
  deploy/helm/ethereum/Chart.yaml
  deploy/helm/ethereum/templates/_helpers.tpl
  deploy/helm/ethereum/templates/ethstats-deployment.yaml
  deploy/helm/ethereum/templates/ethstats-secret.yaml
  deploy/helm/ethereum/templates/ethstats-service.yaml
  deploy/helm/ethereum/templates/geth-deployment.yaml
  deploy/helm/ethereum/templates/geth-pvc.yaml
  deploy/helm/ethereum/templates/geth-service.yaml
  deploy/helm/ethereum/values.yaml
  docs/tutorials/k8s.md
  readme.md
  tools/sifgen/node/node.go
  tools/sifgen/sifgen.go
Labels: Ready for Review

#423 Fetch yq through wget since the latest version has breaking changes
  test/integration/setup-linux-environment-root.sh
Labels: Ready for Review

#350 [Peggy] - Add slither static analysis to CI
  .github/workflows/pull_request.yml
Labels: Ready for Review, github_actions

#421 [Peggy] Integration tests - test chain rollback
  .github/workflows/integrationtest.yml
  smart-contracts/scripts/getIntegrationTestTransactions.js
  test/integration/Dockerfile.testrunner
  test/integration/add-rowan-to-account.sh
  test/integration/add-second-account.sh
  test/integration/apply_ganache_snapshot.sh
  test/integration/assemble_data.sh
  test/integration/docker-compose-ganache.yml
  test/integration/docker-compose-integration.yml
  test/integration/execute_integration_tests_main.sh
  test/integration/execute_integration_tests_whitelisted_validators.sh
  test/integration/initial_test_balances.py
  test/integration/integration-entrypoint.sh
  test/integration/setup-linux-environment-root.sh
  test/integration/setup_sifchain.sh
  test/integration/shell_utilities.sh
  test/integration/sifchain_logs.sh
  test/integration/sifchain_start_daemon.sh
  test/integration/sifchain_start_ebrelayer.sh
  test/integration/snapshot_ganache_chain.sh
  test/integration/start-ganache-port-forwarding.sh
  test/integration/start-integration-env.sh
  test/integration/start_watchers.sh
  test/integration/stop_watchers.sh
  test/integration/test_chain_rollback.py
  test/integration/test_utilities.py
  test/integration/vagrant/.gitignore
  test/integration/vagrant/Makefile
  test/integration/wait_for_sif_account.py
Labels: Ready for Review

#425 [ChainOps] ETH Updates
  deploy/helm/ethereum/templates/geth-deployment.yaml
  deploy/helm/ethereum/values.yaml
  deploy/rake/cluster.rake
Labels: Ready for Review

#418 [ChainOps] Doc tweaks.
  docs/tutorials/k8s.md
Labels: Ready for Review

#435 [Peggy] Minor integration test cleanup
  smart-contracts/Makefile
  test/integration/Makefile
  test/integration/assemble_data.sh
  test/integration/execute_integration_tests_main.sh
  test/integration/sifchain_logs.sh
  test/integration/start-integration-env.sh
  test/integration/vagrant/.gitignore
  test/integration/vagrant/Makefile
Labels: Ready for Review

#363 [Peggy] Update limits for smart contract deposits
  smart-contracts/LimitUpdating.md
  smart-contracts/Whitelist.md
  smart-contracts/contracts/BridgeBank/BankStorage.sol
  smart-contracts/contracts/BridgeBank/BridgeBank.sol
  smart-contracts/contracts/BridgeBank/EthereumBank.sol
  smart-contracts/data/limitWhitelistUpdate.json
  smart-contracts/migrations/2_next.js
  smart-contracts/scripts/bulkSetTokenLockBurnLimit.js
  smart-contracts/scripts/getBridgeAddress.js
  smart-contracts/scripts/getBridgeRegistryAddress.js
  smart-contracts/scripts/getTokenBalance.js
  smart-contracts/scripts/getTokenContractAddress.js
  smart-contracts/scripts/getTxReceipt.js
  smart-contracts/scripts/getValidators.js
  smart-contracts/scripts/hasLockedTokens.js
  smart-contracts/scripts/mintTestTokens.js
  smart-contracts/scripts/sendAddBridgeToken.js
  smart-contracts/scripts/sendApproveTx.js
  smart-contracts/scripts/sendCheckProphecy.js
  smart-contracts/scripts/sendProcessProphecy.js
  smart-contracts/scripts/sendUpdateWhiteList.js
  smart-contracts/scripts/setTokenLockBurnLimit.js
  smart-contracts/test/test_bridgeBank.js
  smart-contracts/test/test_cosmosBridge.js
  smart-contracts/test/test_end_to_end.js
  smart-contracts/test/test_security.js
  smart-contracts/yarn.lock
  test/integration/start-integration-env.sh
Labels: Ready for Review
