Repository Sifchain/sifnode, pull requests merged in 2021-02, with the labels that each got.

#625 [ChainOps] LCD Init fixes.
  deploy/helm/sifnode/templates/sifnodecli-deployment.yaml
Labels: Ready for Review

#541 update arch doc with adr changes
  docs/clp/Liquidity Pools Architecture.md
  docs/clp/clp-adr.md
Labels: documentation

#647 [ChainOps] Missing gas for the relayer.
  deploy/helm/ebrelayer/templates/deployment.yaml
  deploy/helm/ebrelayer/values.yaml
Labels: Ready for Review

#559 Feature/clp test tables
  test/test-tables/doubleswap_liquidityfees.json
  test/test-tables/doubleswap_result.json
  test/test-tables/doubleswap_standardslip.json
  test/test-tables/pool_units.json
  test/test-tables/reverse_double_swap_result.json
  test/test-tables/reverse_single_swap_result.json
  test/test-tables/sample_liquidity_fee.json
  test/test-tables/sample_swaps.json
  test/test-tables/singleswap_liquidityfees.json
  test/test-tables/singleswap_result.json
  test/test-tables/singleswap_standardslip.json
  ui/core/src/entities/formulae.calculateExternalExternalSwapResult.test.ts
  ui/core/src/entities/formulae.calculateLiquidityProviderFee.test.ts
  ui/core/src/entities/formulae.calculateLiquidityProviderUnits.test.ts
  ui/core/src/entities/formulae.calculatePriceImpact.test.ts
Labels: Ready for Review

#654 [ChainOps] Governance voting parameters.
  deploy/helm/sifnode/templates/deployment.yaml
  deploy/helm/sifnode/values.yaml
Labels: Ready for Review

#481 Feature tx replay
  cmd/ebrelayer/main.go
  cmd/ebrelayer/relayer/cosmos.go
  cmd/ebrelayer/relayer/cosmos_test.go
  cmd/ebrelayer/relayer/ethereum.go
  cmd/ebrelayer/relayer/ethereum_test.go
  cmd/ebrelayer/relayer/network.go
  cmd/ebrelayer/relayer/network_test.go
  cmd/ebrelayer/replay.go
  cmd/ebrelayer/txs/parser.go
  cmd/ebrelayer/txs/parser_test.go
  cmd/ebrelayer/txs/test_common.go
  cmd/ebrelayer/types/types.go
  docs/relayer/replay-instruction.md
  test/integration/assemble_data.sh
  test/integration/sifchain_blocks.sh
  test/integration/src/py/conftest.py
  test/integration/src/py/test_ebrelayer_replay.py
  x/ethbridge/handler.go
  x/ethbridge/handler_test.go
  x/ethbridge/types/events.go
Labels: in progress

#675 Remove slither workflow - we don't use the automated version of this.
  .github/workflows/pull_request.yml
Labels: Ready for Review

#679 [ChainOps] Voting period.
  deploy/helm/sifnode/values.yaml
Labels: Ready for Review

#682 [ChainOps] Sifchain smart contracts.
  smart-contracts/deployments/sifchain/.openzeppelin/mainnet.json
  smart-contracts/deployments/sifchain/.openzeppelin/unknown-1337.json
  smart-contracts/deployments/sifchain/BridgeBank.json
  smart-contracts/deployments/sifchain/BridgeRegistry.json
  smart-contracts/deployments/sifchain/CosmosBridge.json
  smart-contracts/deployments/sifchain/Migrations.json
  smart-contracts/deployments/sifchain/build/contracts/Address.json
  smart-contracts/deployments/sifchain/build/contracts/BankStorage.json
  smart-contracts/deployments/sifchain/build/contracts/BridgeBank.json
  smart-contracts/deployments/sifchain/build/contracts/BridgeRegistry.json
  smart-contracts/deployments/sifchain/build/contracts/BridgeToken.json
  smart-contracts/deployments/sifchain/build/contracts/Context.json
  smart-contracts/deployments/sifchain/build/contracts/CosmosBank.json
  smart-contracts/deployments/sifchain/build/contracts/CosmosBankStorage.json
  smart-contracts/deployments/sifchain/build/contracts/CosmosBridge.json
  smart-contracts/deployments/sifchain/build/contracts/CosmosBridgeStorage.json
  smart-contracts/deployments/sifchain/build/contracts/CosmosWhiteList.json
  smart-contracts/deployments/sifchain/build/contracts/CosmosWhiteListStorage.json
  smart-contracts/deployments/sifchain/build/contracts/ERC20.json
  smart-contracts/deployments/sifchain/build/contracts/ERC20Burnable.json
  smart-contracts/deployments/sifchain/build/contracts/ERC20Detailed.json
  smart-contracts/deployments/sifchain/build/contracts/ERC20Mintable.json
  smart-contracts/deployments/sifchain/build/contracts/ERC20UNSAFE.json
  smart-contracts/deployments/sifchain/build/contracts/EthereumBank.json
  smart-contracts/deployments/sifchain/build/contracts/EthereumBankStorage.json
  smart-contracts/deployments/sifchain/build/contracts/EthereumWhiteList.json
  smart-contracts/deployments/sifchain/build/contracts/IERC20.json
  smart-contracts/deployments/sifchain/build/contracts/Migrations.json
  smart-contracts/deployments/sifchain/build/contracts/MinterRole.json
  smart-contracts/deployments/sifchain/build/contracts/MockCosmosBridgeUpgrade.json
  smart-contracts/deployments/sifchain/build/contracts/Oracle.json
  smart-contracts/deployments/sifchain/build/contracts/OracleStorage.json
  smart-contracts/deployments/sifchain/build/contracts/Pausable.json
  smart-contracts/deployments/sifchain/build/contracts/PauserRole.json
  smart-contracts/deployments/sifchain/build/contracts/Roles.json
  smart-contracts/deployments/sifchain/build/contracts/SafeERC20.json
  smart-contracts/deployments/sifchain/build/contracts/SafeMath.json
  smart-contracts/deployments/sifchain/build/contracts/ToLower.json
  smart-contracts/deployments/sifchain/build/contracts/Valset.json
  smart-contracts/deployments/sifchain/build/contracts/ValsetStorage.json
  smart-contracts/truffle-config.js
Labels: Ready for Review

#683 [ChainOps] eRowan tweaks.
  smart-contracts/scripts/setup_eRowan.js
Labels: Ready for Review

#692 [ChainOps] Mint/bond args.
  deploy/helm/sifnode/templates/deployment.yaml
  deploy/helm/sifnode/values.yaml
Labels: Ready for Review

#704 [ChainOps] Faucet.
  .github/workflows/release.yml
  Makefile
  tools/sifgen/node/node.go
Labels: Ready for Review

#706 [ChainOps] Release fixes.
  .github/workflows/release.yml
Labels: Ready for Review

#709 [ChainOps] Release fixes.
  .github/workflows/release.yml
Labels: Ready for Review

#713 [ChainOps] Peggy memory updates.
  .github/workflows/feature.yml
  deploy/helm/ebrelayer/values.yaml
  deploy/terraform/providers/aws/variables.tf
Labels: Ready for Review

#726 [ChainOps] Force the EKS module version.
  deploy/terraform/providers/aws/main.tf
Labels: Ready for Review

#721 [ChainOps] Block explorer fixes.
  deploy/helm/block-explorer/templates/service.yaml
  deploy/helm/block-explorer/values.yaml
  deploy/rake/cluster.rake
Labels: Ready for Review

#741 [ChainOps] Upgrade
  app/app.go
Labels: Ready for Review

#701 [ui] Added config to update cloudflare dnslink records
  .github/workflows/pinata-build-deploy-ui.yml
Labels: in progress

#750 Token decimals normalization
  test/test-tables/doubleswap_liquidityfees.json
  test/test-tables/doubleswap_result.json
  test/test-tables/doubleswap_standardslip.json
  test/test-tables/pool_units.json
  test/test-tables/singleswap_liquidityfees.json
  test/test-tables/singleswap_result.json
  test/test-tables/singleswap_standardslip.json
  ui/core/src/entities/Pool.test.ts
  ui/core/src/entities/Pool.ts
  ui/core/src/entities/formulae.calculateExternalExternalSwapResult.test.ts
  ui/core/src/entities/formulae.calculateLiquidityProviderFee.test.ts
  ui/core/src/entities/formulae.ts
  ui/core/src/hooks/addLiquidityCalculator.test.ts
  ui/core/src/hooks/addLiquidityCalculator.ts
  x/clp/alias.go
  x/clp/handler.go
  x/clp/keeper/calculations.go
  x/clp/keeper/table_test.go
  x/clp/types/keys.go
Labels: Under Review

#733 [ChainOps] Documentation updates.
  deploy/rake/cluster.rake
  deploy/rake/genesis.rake
  deploy/rake/helpers.rake
  deploy/rake/validator.rake
  docs/README.md
  docs/chainOps/ChainOps-manual.md
  docs/chainOps/Genesis.md
  docs/chainOps/Upgrades.md
  docs/chainOps/k8s/README.md
  docs/chainOps/k8s/tutorials/betanet.md
  docs/chainOps/k8s/tutorials/testnet.md
  docs/chainOps/standalone/README.md
  docs/chainOps/standalone/tutorials/betanet.md
  docs/chainOps/standalone/tutorials/testnet.md
  readme.md
Labels: Ready for Review

#754 Update docs for peggy
  docs/peggy/Peggy-Arch.md
  docs/peggy/Peggy-Important-Notes.md
  docs/peggy/Peggy-Smart-Contract-Pausing.md
  docs/peggy/adr-002-ebrelayer-eth-subscribe.md
Labels: Ready for Review

#725 [Peggy] (not required for alpha) Use a different address for the validator's ethereum address
  .github/workflows/integrationtest.yml
  smart-contracts/scripts/test/enableNewToken.js
  smart-contracts/scripts/test/sendLockTx.js
  test/integration/execute_integration_tests_against_any_chain.sh
  test/integration/execute_integration_tests_against_test_chain.sh
  test/integration/execute_integration_tests_whitelisted_validators.sh
  test/integration/ganache_start.sh
  test/integration/samplecmds.sh
  test/integration/sifchain_run_ebrelayer.sh
  test/integration/src/py/conftest.py
  test/integration/src/py/no_whitelisted_validators.py
  test/integration/src/py/pytest_utilities.py
  test/integration/src/py/test_no_whitelisted_validators.py
  test/integration/src/py/test_random_currency_roundtrip.py
  test/integration/start-integration-env.sh
Labels: Ready for Review

#659 [Peggy] Update integration tests to work against non-local chain
  smart-contracts/scripts/test/contractUtilities.js
  smart-contracts/scripts/test/getTokenBalance.js
  smart-contracts/scripts/test/sifchainUtilities.js
  test/integration/README.md
  test/integration/src/py/burn_lock_functions.py
  test/integration/src/py/conftest.py
  test/integration/src/py/sifchain_to_ethereum.py
  test/integration/src/py/sifchain_to_sifchain.py
  test/integration/src/py/test_bulk_transfers.py
  test/integration/src/py/test_ebrelayer_replay.py
  test/integration/src/py/test_ebrelayer_restart.py
  test/integration/src/py/test_eth_transfers.py
  test/integration/src/py/test_new_currency_transfers.py
  test/integration/src/py/test_random_currency_roundtrip.py
  test/integration/src/py/test_rollback_chain.py
  test/integration/src/py/test_utilities.py
Labels: Ready for Review

#771 [ChainOps] Doc fixes.
  docs/chainOps/k8s/tutorials/betanet.md
  docs/chainOps/standalone/tutorials/betanet.md
Labels: Ready for Review

#763 More fixes
  ui/app/src/components/poolStats/PoolStatsListItem.vue
  ui/app/src/components/shared/DetailsPanelPool.vue
  ui/app/src/components/shared/Tabs.vue
  ui/app/src/components/shared/utils.ts
  ui/app/src/views/CreatePoolPage.vue
  ui/app/src/views/PegAssetPage.vue
  ui/app/src/views/PegListingPage.vue
  ui/app/src/views/SwapPage.vue
  ui/core/src/assets.sifchain.sandpit.json
  ui/core/src/hooks/addLiquidityCalculator.test.ts
  ui/core/src/hooks/addLiquidityCalculator.ts
  ui/core/src/hooks/removeLiquidityCalculator.ts
  ui/core/src/hooks/swapCalculator.ts
Labels: frontend, golive

#777 [Peggy] Integration tests enhanced currency tests for sandpit
  smart-contracts/scripts/test/contractUtilities.js
  smart-contracts/scripts/test/enableNewToken.js
  smart-contracts/scripts/test/sifchainUtilities.js
  test/integration/src/py/burn_lock_functions.py
  test/integration/src/py/conftest.py
  test/integration/src/py/test_new_currency_transfers.py
  test/integration/src/py/test_utilities.py
Labels: Ready for Review

#779 Fix issue with tabs showing the wrong peg/unpeg buttons. Remove bad config
  ui/app/src/components/shared/Tabs.vue
  ui/app/src/views/PegListingPage.vue
  ui/core/src/assets.ethereum.localnet.json
Labels: frontend, golive

#773 [ui] feature/rewards-url
  ui/app/src/components/layout/Layout.vue
  ui/app/src/components/shared/Menu.vue
  ui/app/src/router/index.ts
  ui/app/src/views/PoolPage.vue
  ui/app/src/views/RewardsPage.vue
  ui/app/src/views/SinglePool.vue
Labels: frontend, golive

#774 [ChainOps] Monitoring.
  deploy/helm/logstash/.helmignore
  deploy/helm/logstash/Chart.yaml
  deploy/helm/logstash/templates/NOTES.txt
  deploy/helm/logstash/templates/_helpers.tpl
  deploy/helm/logstash/templates/configmap-config.yaml
  deploy/helm/logstash/templates/configmap-pipeline.yaml
  deploy/helm/logstash/templates/daemonset.yaml
  deploy/helm/logstash/templates/ingress.yaml
  deploy/helm/logstash/templates/poddisruptionbudget.yaml
  deploy/helm/logstash/templates/podsecuritypolicy.yaml
  deploy/helm/logstash/templates/role.yaml
  deploy/helm/logstash/templates/rolebinding.yaml
  deploy/helm/logstash/templates/secret.yaml
  deploy/helm/logstash/templates/service-headless.yaml
  deploy/helm/logstash/templates/service.yaml
  deploy/helm/logstash/templates/serviceaccount.yaml
  deploy/helm/logstash/values.yaml
  deploy/rake/cluster.rake
Labels: Ready for Review

#791 Fixed typo, token name was "Bancor Network Toke" in json
  ui/core/src/assets.sifchain.mainnet.json
  ui/core/src/assets.sifchain.sandpit.json
Labels: Ready for Review

#781 [ui] (Not for go live) Silently guard against pools with weird tokens
  ui/core/src/api/ClpService/ClpService.ts
  ui/core/src/api/utils/SifClient/toPool.ts
Labels: frontend

#796 [ui] core/ethBridgeService: hard code gas limit for burn
  ui/core/src/api/EthbridgeService/EthbridgeService.ts
Labels: bug, frontend

#797 [ChainOps] Docker for the community.
  deploy/docker/mainnet/docker-compose.yml
  deploy/docker/mainnet/entrypoint.sh
  deploy/rake/genesis.rake
  docs/chainOps/standalone/README.md
  docs/chainOps/standalone/tutorials/betanet.md
  docs/chainOps/standalone/tutorials/testnet.md
Labels: Ready for Review

#815 Merge master back to develop
  ui/app/src/views/CreatePoolPage.vue
  ui/app/src/views/PoolPage.vue
  ui/app/src/views/SinglePool.vue
  ui/core/src/actions/clp/index.ts
  ui/core/src/assets.ethereum.localnet.json
  ui/core/src/store/index.ts
  ui/core/src/store/pools.ts
Labels: Ready for Review

#785 [ui] added connect wallet to pool page
  ui/app/src/views/PoolPage.vue
Labels: frontend

#827 [ChainOps] Latest release.
  app/app.go
Labels: Ready for Review

#833 [Peggy] Integration tests - test_liquidity_pools.py should run in github actions
  test/integration/execute_integration_tests_against_test_chain.sh
Labels: Ready for Review

#831 [Peggy] Integration tests don't need to run on checkins to the ui tree
  .github/workflows/integrationtest.yml
Labels: Ready for Review

#845 Update slip adjustment
  test/test-tables/pool_units.json
  ui/core/src/entities/Pool.test.ts
  ui/core/src/entities/formulae.ts
  ui/core/src/hooks/addLiquidityCalculator.test.ts
  x/clp/keeper/calculations.go
  x/clp/keeper/table_test.go
Labels: P1, Ready for Review

#847 [ui] chore/tooltip-unpeg
  ui/app/src/components/shared/DetailsTable.vue
  ui/app/src/views/PegAssetPage.vue
Labels: Ready for Review, frontend

#837 [ui] app/panel: overflow: scroll
  ui/app/src/components/shared/Panel.vue
Labels: frontend

#835 [ui] core/ethBridgeService: use allowance for all erc20, solve "double approve" issue
  ui/core/src/api/EthbridgeService/EthbridgeService.ts
Labels: Ready for Review, frontend

#849 fix slip adjust formula docs
  docs/clp/Liquidity Pools Architecture.md
  docs/clp/clp-adr.md
Labels: Ready for Review, documentation

#856 revert formula
  test/test-tables/pool_units.json
  ui/core/src/entities/Pool.test.ts
  ui/core/src/entities/formulae.ts
  ui/core/src/hooks/addLiquidityCalculator.test.ts
  x/clp/keeper/calculations.go
Labels: in progress

#858 [ChainOps] Remove upgrade handler.
  app/app.go
Labels: Ready for Review

#863 [Peggy] Minor fixes to integration tests
  smart-contracts/scripts/test/enableNewToken.js
  test/integration/src/py/test_bulk_transfers.py
  test/integration/src/py/test_eth_transfers.py
  test/integration/src/py/test_fanout_sifchain_account.py
  test/integration/src/py/test_liquidity_pools.py
  test/integration/src/py/test_simple.py
  test/integration/src/py/token_setup.py
Labels: Ready for Review

#861 [ui] "double approve" - core/EthBridgeService: fix types/logic
  ui/core/src/api/EthbridgeService/EthbridgeService.ts
Labels: Ready for Review, frontend
