Repository Sifchain/sifnode, pull requests merged in 2021-09, with the labels that each got.

#1836 Inflationary Block Rewards
  app/app.go
  app/setup_handlers.go
  cmd/sifnoded/cmd/migrate_test.go
  cmd/sifnoded/cmd/testdata/v039_exported_migrated_state.json
  tools/sifgen/common/types/genesis.go
  tools/sifgen/genesis/genesis.go
  tools/sifgen/network/network.go
  version
Labels: Ready for Review, Sifnode

#1809 Prebuild ibc tokens
  smart-contracts/AddIbcTokens.md
  smart-contracts/data/ibc_mainnet_tokens.json
  smart-contracts/data/ibc_token_addresses.jsonl
  smart-contracts/hardhat.config.ts
  smart-contracts/package.json
  smart-contracts/scripts/attach_ibc_matching_token.ts
  smart-contracts/scripts/create_ibc_matching_token.ts
  smart-contracts/scripts/fixup_atom_roles.ts
  smart-contracts/src/contractSupport.ts
  smart-contracts/src/hardhatFunctions.ts
  smart-contracts/src/ibcMatchingTokens.ts
  smart-contracts/src/tsyringe/contracts.ts
  smart-contracts/test/test_ibcMatchingTokens.ts
  smart-contracts/test_data/ibc_token_addresses.jsonl
  smart-contracts/test_data/ibc_token_data.json
  smart-contracts/test_data/sifnode-devnet-1-symbol_translator.json
  smart-contracts/tsconfig.json
  test/integration/environment_setup.sh
Labels: Peggy

#1837 Added a script to go from a list of urls in parens to token addresses
  smart-contracts/scripts/urls_to_token_addresses.sh
Labels: Peggy

#1863 osmosis whitelist devnet
  scripts/ibc/tokenregistration/generate-devnet.sh
  scripts/ibc/tokenregistration/sifchain-devnet-1/osmosis.json
Labels: Sifnode

#1868 remove incorrect entries
  scripts/ibc/tokenregistration/sifchain-1/sifchain-1-tokenregistry.json
Labels: Sifnode

#1871 Remove the metadata module and use token registry
  .golangci.yml
  app/app.go
  cmd/ebrelayer/types/types.go
  proto/sifnode/dispensation/v1/types.proto
  proto/sifnode/ethbridge/v1/query.proto
  proto/sifnode/ethbridge/v1/tx.proto
  proto/sifnode/ethbridge/v1/types.proto
  proto/sifnode/tokenregistry/v1/query.proto
  proto/sifnode/tokenregistry/v1/tx.proto
  proto/sifnode/tokenregistry/v1/types.proto
  x/clp/handler_test.go
  x/clp/test/test_common.go
  x/clp/types/keys.go
  x/clp/types/querier.pb.gw.go
  x/dispensation/types/msgs_test.go
  x/ethbridge/client/cli/tx.go
  x/ethbridge/client/module_client.go
  x/ethbridge/client/rest/rest.go
  x/ethbridge/handler.go
  x/ethbridge/handler_test.go
  x/ethbridge/keeper/keeper.go
  x/ethbridge/keeper/keeper_test.go
  x/ethbridge/keeper/metadata.go
  x/ethbridge/keeper/metadata_test.go
  x/ethbridge/keeper/msg_server.go
  x/ethbridge/test/test_helpers.go
  x/ethbridge/types/claim.go
  x/ethbridge/types/expected_keepers.go
  x/ethbridge/types/msgs.go
  x/ethbridge/types/query.pb.go
  x/ethbridge/types/test_common.go
  x/ethbridge/types/tx.pb.go
  x/ethbridge/types/types.pb.go
  x/ibctransfer/keeper/msg_server.go
  x/ibctransfer/keeper/msg_server_test.go
  x/ibctransfer/onrecv_whitelist.go
  x/ibctransfer/onrecv_whitelist_test.go
  x/tokenregistry/client/cli/metadata.go
  x/tokenregistry/client/cli/query.go
  x/tokenregistry/client/cli/tx.go
  x/tokenregistry/handler/handler.go
  x/tokenregistry/keeper/grpc_metadata.go
  x/tokenregistry/keeper/grpc_query.go
  x/tokenregistry/keeper/keeper.go
  x/tokenregistry/keeper/keeper_test.go
  x/tokenregistry/keeper/metadata.go
  x/tokenregistry/keeper/metadata_test.go
  x/tokenregistry/keeper/msg_server.go
  x/tokenregistry/types/expected_keepers.go
  x/tokenregistry/types/genesis.go
  x/tokenregistry/types/mock/keeper_gen.go
  x/tokenregistry/types/msgs.go
  x/tokenregistry/types/query.pb.gw.go
  x/tokenregistry/types/tx.pb.go
  x/tokenregistry/types/types.go
  x/tokenregistry/types/types.pb.go
Labels: Peggy, Peggy 2.0

#1895 Unified command to whitelist tokens
  smart-contracts/Whitelist_Update.md
  smart-contracts/data/whitelist_mainnet_update_17_Sep_2021.json
  smart-contracts/package.json
  smart-contracts/scripts/bulk_set_whitelist.ts
  smart-contracts/scripts/fetchTokenDetails.js
Labels: Peggy

#1949 devenv writes to different log files for ebrelayer, witness, sifnoded
  cmd/ebrelayer/main.go
  smart-contracts/package-lock.json
  smart-contracts/package.json
  smart-contracts/scripts/devenv.ts
  smart-contracts/src/devenv/ebrelayer.ts
  smart-contracts/src/devenv/sifnoded.ts
  smart-contracts/yarn.lock
Labels: Peggy, Peggy 2.0
