Repository Sifchain/sifnode, pull requests merged in 2021-01, with the labels that each got.

#428 [ChainOps] Cosmovisor
  cmd/sifgen/main.go
  cmd/sifnoded/Dockerfile
  deploy/helm/sifnode/templates/sifnode-deployment.yaml
  deploy/helm/sifnode/values.yaml
  tools/sifgen/node/node.go
  tools/sifgen/sifgen.go
  tools/sifgen/utils/cli.go
Labels: Ready for Review

#433 [Peggy] Integration tests need to use a slightly larger amount to work around javascript issues
  test/integration/test_chain_rollback.py
Labels: Ready for Review

#437 [Peggy] Added integration test case for sending eth over limit
  test/integration/peggy-e2e-test.py
Labels: Ready for Review

#439 [ChainOps] Sandpit Smart Contracts.
  smart-contracts/deployments/sandpit/.openzeppelin/ropsten.json
  smart-contracts/deployments/sandpit/.openzeppelin/unknown-1337.json
  smart-contracts/deployments/sandpit/BridgeBank.json
  smart-contracts/deployments/sandpit/BridgeRegistry.json
  smart-contracts/deployments/sandpit/BridgeToken.json
  smart-contracts/deployments/sandpit/CosmosBridge.json
  smart-contracts/deployments/sandpit/Migrations.json
  smart-contracts/deployments/sandpit/Oracle.json
  smart-contracts/deployments/sandpit/Valset.json
Labels: Ready for Review

#438 [ChainOps] README updates.
  readme.md
Labels: Ready for Review

#436 [ChainOps] Deployment bugfixes.
  deploy/helm/sifnode/values.yaml
  deploy/rake/cluster.rake
  deploy/rake/validator.rake
Labels: Ready for Review

#440 [ChainOps] Terraform tweaks.
  deploy/terraform/providers/aws/variables.tf
Labels: Ready for Review

#448 [Frontend] Fix swap not working because pools not loading
  ui/core/src/actions/clp/index.ts
  ui/core/src/api/ClpService/ClpService.ts
  ui/core/src/api/SifService/SifService.ts
Labels: bug

#432 [Github Actions] Feature/Vercel GitHub Action Autodeploy
  .github/workflows/vercel-deploy-ui.yml
  .gitignore
  ui/core/src/assets.sifchain.localnet.json
  ui/core/src/config.testnet.json
  ui/vercel.json
Labels: github_actions

#455 [ChainOps] CLP Genesis Updates
  cmd/sifgen/main.go
  deploy/helm/sifnode/templates/sifnode-deployment.yaml
  deploy/helm/sifnode/values.yaml
  deploy/rake/cluster.rake
  tools/sifgen/common/common.go
  tools/sifgen/common/types/genesis.go
  tools/sifgen/genesis/genesis.go
  tools/sifgen/node/node.go
  tools/sifgen/sifgen.go
  tools/sifgen/utils/cli.go
Labels: Ready for Review

#476 [Peggy] Removed test artifacts that were checked in accidentally
  test/integration/vagrant/data/bridgebank.txt
  test/integration/vagrant/data/env
  test/integration/vagrant/data/ganachelog.txt
  test/integration/vagrant/data/testrun.sh
  test/integration/vagrant/datafiles.12-18-22-29-00.tar
  test/integration/vagrant/datafiles.12-18-22-49-53.tar
  test/integration/vagrant/datafiles.tar
  test/integration/vagrantenv.sh
Labels: Ready for Review

#475 [ChainOps] Upgrade docs.
  .github/workflows/release.yml
  docs/chainOps/Upgrades.md
Labels: Ready for Review

#483 [ChainOps] Eth mainnet tweaks.
  deploy/helm/ethereum/templates/geth-deployment.yaml
  deploy/helm/ethereum/values.yaml
  deploy/rake/cluster.rake
Labels: Ready for Review

#336 Feature/Upgrade Module
  app/app.go
  app/app_test.go
  scripts/init.sh
  scripts/restartafterUpgrade.sh
  scripts/upgrade.sh
  test/integration/__pycache__/test_utilities.cpython-38.pyc
  tools/sifgen/common/types/genesis.go
  x/oracle/keeper/validatorWhiteList.go
Labels: in progress

#484 [ChainOps] Genesis updates.
  cmd/sifgen/main.go
  deploy/helm/sifnode/templates/sifnode-deployment.yaml
  deploy/helm/sifnode/values.yaml
  deploy/rake/cluster.rake
  tools/sifgen/common/common.go
  tools/sifgen/common/types/genesis.go
  tools/sifgen/network/network.go
  tools/sifgen/network/network_test.go
  tools/sifgen/node/node.go
  tools/sifgen/sifgen.go
Labels: Ready for Review

#498 [ChainOps] Sandpit contracts.
  smart-contracts/deployments/sandpit/.openzeppelin/ropsten.json
  smart-contracts/deployments/sandpit/.openzeppelin/unknown-1337.json
  smart-contracts/deployments/sandpit/BridgeBank.json
  smart-contracts/deployments/sandpit/BridgeRegistry.json
  smart-contracts/deployments/sandpit/BridgeToken.json
  smart-contracts/deployments/sandpit/CosmosBridge.json
  smart-contracts/deployments/sandpit/Migrations.json
  smart-contracts/deployments/sandpit/Oracle.json
  smart-contracts/deployments/sandpit/Valset.json
Labels: Ready for Review

#500 [ChainOps] Sifgen hotfix.
  cmd/sifgen/main.go
  tools/sifgen/common/types/genesis.go
Labels: Ready for Review

#474 [Peggy] Feature/integration test ropsten support
  .github/workflows/integrationtest.yml
  smart-contracts/package.json
  smart-contracts/scripts/sendLockTx.js
  smart-contracts/scripts/test/contractUtilities.js
  smart-contracts/scripts/test/getTokenBalance.js
  smart-contracts/scripts/test/sendLockTx.js
  smart-contracts/scripts/test/sifchainUtilities.js
  smart-contracts/scripts/test/waitForBlock.js
  test/integration/Makefile
  test/integration/README.md
  test/integration/assemble_data.sh
  test/integration/execute_integration_tests_against_any_chain.sh
  test/integration/execute_integration_tests_against_test_chain.sh
  test/integration/execute_integration_tests_main.sh
  test/integration/execute_integration_tests_whitelisted_validators.sh
  test/integration/get_eth_balance.sh
  test/integration/initial_test_balances.py
  test/integration/no_whitelisted_validators.py
  test/integration/peggy-basic-test-docker.py
  test/integration/peggy-basic-test.py
  test/integration/peggy-e2e-test.py
  test/integration/samplecmds.sh
  test/integration/setup-linux-environment-user.sh
  test/integration/sifchain_start_ebrelayer.sh
  test/integration/src/py/.gitignore
  test/integration/src/py/burn_lock_functions.py
  test/integration/src/py/ethereum_to_sifchain.py
  test/integration/src/py/initial_test_balances.py
  test/integration/src/py/integration_env_credentials.py
  test/integration/src/py/no_whitelisted_validators.py
  test/integration/src/py/pytest_utilities.py
  test/integration/src/py/sifchain_to_ethereum.py
  test/integration/src/py/sifchain_to_sifchain.py
  test/integration/src/py/test_eth_transfers.py
  test/integration/src/py/test_peggy_fees.py
  test/integration/src/py/test_rollback_chain.py
  test/integration/src/py/test_rowan_transfers.py
  test/integration/src/py/test_transfers.py
  test/integration/src/py/test_utilities.py
  test/integration/src/py/wait_for_sif_account.py
  test/integration/start-integration-env.sh
  test/integration/test_chain_rollback.py
  test/integration/test_utilities.py
  test/integration/vagrant/Makefile
Labels: Ready for Review

#506 [ui] bug/dev-chain-migrate
  ui/chains/peggy/migrate.sh
  ui/package.json
  ui/yarn.lock
Labels: bug, frontend

#504 [Peggy] Integration tests check that we don't charge too much or too little
  test/integration/src/py/test_peggy_fees.py
  test/integration/src/py/test_rowan_transfers.py
Labels: Ready for Review

#512 [ChainOps] Correctly set the peer IP address.
  cmd/sifgen/main.go
Labels: Ready for Review

#515 [ChainOps] 1e8.
  cmd/sifgen/main.go
  deploy/helm/sifnode/values.yaml
  deploy/rake/validator.rake
Labels: Ready for Review

#514 [Peggy] Integration tests need to apt install python3-pip
  test/integration/setup-linux-environment-root.sh
Labels: Ready for Review

#523 [ChainOps] Contracts for merry-go-round.
  smart-contracts/deployments/merry-go-round/.openzeppelin/ropsten.json
  smart-contracts/deployments/merry-go-round/.openzeppelin/unknown-1337.json
  smart-contracts/deployments/merry-go-round/BridgeBank.json
  smart-contracts/deployments/merry-go-round/BridgeRegistry.json
  smart-contracts/deployments/merry-go-round/BridgeToken.json
  smart-contracts/deployments/merry-go-round/CosmosBridge.json
  smart-contracts/deployments/merry-go-round/Migrations.json
  smart-contracts/deployments/merry-go-round/Oracle.json
  smart-contracts/deployments/merry-go-round/Valset.json
Labels: Ready for Review

#525 [ChainOps] README updates.
  readme.md
Labels: Ready for Review

#532 [ChainOps] Relayer fixes.
  cmd/ebrelayer/main.go
  deploy/helm/ebrelayer/templates/deployment.yaml
  deploy/helm/ebrelayer/values.yaml
  deploy/rake/cluster.rake
Labels: Ready for Review

#533 [ui] feature/betanet-notice
  ui/app/src/components/CIconLock.vue
  ui/app/src/components/CIconMagic.vue
  ui/app/src/components/CSignIn.vue
  ui/app/src/components/shared/Header.vue
  ui/app/src/components/shared/Menu.vue
  ui/app/src/views/PegListingPage.vue
  ui/app/src/views/PoolPage.vue
Labels: frontend

#543 clp test tables
  test/test-tables/sample_liquidity_fee.json
  test/test-tables/sample_pool_units.json
  test/test-tables/sample_slip.json
  test/test-tables/sample_swaps.json
  test/test-tables/sample_trade_slip.json
Labels: Ready for Review

#535 [ChainOps] Upgrades.
  .github/workflows/release.yml
  app/app.go
  deploy/helm/sifnode/templates/sifnode-deployment.yaml
  deploy/helm/sifnode/values.yaml
  deploy/release/Dockerfile
  deploy/release/action.yml
  deploy/release/entrypoint.sh
  deploy/release/release.sh
  deploy/release/setup-go.sh
  tools/sifgen/genesis/genesis.go
  tools/sifgen/node/node.go
Labels: Ready for Review

#548 [ChainOps] Voting tweaks.
  app/app.go
  deploy/helm/sifnode/templates/sifnode-deployment.yaml
  deploy/helm/sifnode/values.yaml
  tools/sifgen/genesis/genesis.go
Labels: Ready for Review

#549 [ChainOps] Updated sandpit contracts.
  smart-contracts/deployments/sandpit/.openzeppelin/ropsten.json
  smart-contracts/deployments/sandpit/.openzeppelin/unknown-1337.json
  smart-contracts/deployments/sandpit/BridgeBank.json
  smart-contracts/deployments/sandpit/BridgeRegistry.json
  smart-contracts/deployments/sandpit/BridgeToken.json
  smart-contracts/deployments/sandpit/CosmosBridge.json
  smart-contracts/deployments/sandpit/Migrations.json
Labels: Ready for Review

#531 New formulas for swap fees calculation, Show swap fees in the UI
  test/test-tables/sample_liquidity_fee.json
  test/test-tables/sample_price_impact.json
  test/test-tables/sample_swaps.json
  test/test-tables/sample_trade_slip.json
  ui/app/src/components/currencyfield/BalanceField.vue
  ui/app/src/hooks/useCurrencyFieldState.ts
  ui/app/src/views/SwapPage.vue
  ui/app/src/views/Ui.vue
  ui/core/src/entities/Pool.ts
  ui/core/src/entities/formulae.calculateExternalExternalSwapResult.test.ts
  ui/core/src/entities/formulae.calculateLiquidityProviderFee.test.ts
  ui/core/src/entities/formulae.calculatePriceImpact.test.ts
  ui/core/src/entities/formulae.ts
  ui/core/src/hooks/swapCalculator.test.ts
  ui/core/src/hooks/swapCalculator.ts
  ui/core/tsconfig.compile.json
Labels: Ready for Review, Ready for testing

#554 Fix bug in eth-ceth pegging test
  ui/core/src/api/EthbridgeService/EthbridgeService.test.ts
  ui/core/src/api/EthbridgeService/EthbridgeService.ts
  ui/core/src/config.localnet.json
Labels: Ready for Review

#558 [ui] config fixes with updated contracts, and ethereum network
  ui/core/src/assets.ethereum.ropsten.json
  ui/core/src/config.sandpit.json
Labels: bug

#550 [UI] Display fee to user for unpeg transaction
  ui/app/src/components/shared/DetailsTable.vue
  ui/app/src/views/PegAssetPage.vue
  ui/core/src/actions/peg/index.ts
  ui/core/src/entities/AssetAmount.ts
Labels: Ready for Review

#563 [ChainOps] Upgrade tweaks.
  app/app.go
  deploy/release/release.sh
  tools/sifgen/node/node.go
Labels: Ready for Review

#566 [ChainOps] README fixes.
  readme.md
Labels: Ready for Review

#564 [Peggy] Integrationtest/paralleleth
  smart-contracts/package.json
  smart-contracts/scripts/test/approve.js
  smart-contracts/scripts/test/getTokenBalance.js
  smart-contracts/scripts/test/sendBurnTx.js
  smart-contracts/scripts/test/sendLockTx.js
  smart-contracts/scripts/test/sifchainUtilities.js
  smart-contracts/truffle-config.js
  test/integration/Dockerfile.devenv
  test/integration/apply_ganache_snapshot.sh
  test/integration/docker-compose-ganache.yml
  test/integration/execute_integration_tests_against_test_chain.sh
  test/integration/ganache_start.sh
  test/integration/setup-linux-environment-root.sh
  test/integration/setup-linux-environment-user.sh
  test/integration/setup-linux-environment.sh
  test/integration/smart_contract_env.sh
  test/integration/src/py/burn_lock_functions.py
  test/integration/src/py/test_eth_transfers.py
  test/integration/src/py/test_parallel_eth_transfers.py
  test/integration/src/py/test_peggy_fees.py
  test/integration/src/py/test_rollback_chain.py
  test/integration/src/py/test_rowan_transfers.py
  test/integration/src/py/test_utilities.py
  test/integration/start-integration-env.sh
  test/integration/vagrant/Makefile
Labels: Ready for Review

#575 [ChainOps] Smart contracts for merry-go-round.
  smart-contracts/deployments/merry-go-round/.openzeppelin/ropsten.json
  smart-contracts/deployments/merry-go-round/.openzeppelin/unknown-1337.json
  smart-contracts/deployments/merry-go-round/BridgeBank.json
  smart-contracts/deployments/merry-go-round/BridgeRegistry.json
  smart-contracts/deployments/merry-go-round/BridgeToken.json
  smart-contracts/deployments/merry-go-round/CosmosBridge.json
  smart-contracts/deployments/merry-go-round/Migrations.json
Labels: Ready for Review

#576 [ChainOps] README updates.
  readme.md
Labels: Ready for Review

#579 [Frontend] Feature/error notifications
  ui/app/src/components/Notifications.vue
  ui/app/src/views/CreatePoolPage.vue
  ui/app/src/views/RemoveLiquidityPage.vue
  ui/app/src/views/SwapPage.vue
  ui/core/src/actions/clp/index.ts
  ui/core/src/actions/peg/index.ts
  ui/core/src/api/SifService/SifService.ts
  ui/core/src/api/utils/Notifications.ts
Labels: Ready for Review

#573 [Frontend] Display liquidity provider percent based on total liquidity provider units
  ui/app/src/views/CreatePoolPage.vue
  ui/core/src/entities/LiquidityProvider.ts
  ui/core/src/entities/Pool.ts
  ui/core/src/hooks/addLiquidityCalculator.test.ts
  ui/core/src/hooks/addLiquidityCalculator.ts
Labels: Ready for Review

#578 [Frontend] Fix max button
  ui/app/src/views/CreatePoolPage.vue
  ui/app/src/views/SwapPage.vue
  ui/core/src/entities/AssetAmount.ts
  ui/core/src/entities/fraction/Fraction.ts
  ui/core/src/hooks/addLiquidityCalculator.test.ts
  ui/core/src/hooks/addLiquidityCalculator.ts
  ui/core/src/hooks/swapCalculator.test.ts
  ui/core/src/hooks/swapCalculator.ts
Labels: Ready for Review

#588 [ChainOps] Updated Sandpit contracts.
  smart-contracts/.gitignore
  smart-contracts/deployments/sandpit/.openzeppelin/ropsten.json
  smart-contracts/deployments/sandpit/.openzeppelin/unknown-1337.json
  smart-contracts/deployments/sandpit/BridgeBank.json
  smart-contracts/deployments/sandpit/BridgeRegistry.json
  smart-contracts/deployments/sandpit/BridgeToken.json
  smart-contracts/deployments/sandpit/CosmosBridge.json
  smart-contracts/deployments/sandpit/Migrations.json
  smart-contracts/deployments/sandpit/build/contracts/Address.json
  smart-contracts/deployments/sandpit/build/contracts/BankStorage.json
  smart-contracts/deployments/sandpit/build/contracts/BridgeBank.json
  smart-contracts/deployments/sandpit/build/contracts/BridgeRegistry.json
  smart-contracts/deployments/sandpit/build/contracts/BridgeToken.json
  smart-contracts/deployments/sandpit/build/contracts/Context.json
  smart-contracts/deployments/sandpit/build/contracts/CosmosBank.json
  smart-contracts/deployments/sandpit/build/contracts/CosmosBankStorage.json
  smart-contracts/deployments/sandpit/build/contracts/CosmosBridge.json
  smart-contracts/deployments/sandpit/build/contracts/CosmosBridgeStorage.json
  smart-contracts/deployments/sandpit/build/contracts/CosmosWhiteList.json
  smart-contracts/deployments/sandpit/build/contracts/CosmosWhiteListStorage.json
  smart-contracts/deployments/sandpit/build/contracts/ERC20.json
  smart-contracts/deployments/sandpit/build/contracts/ERC20Burnable.json
  smart-contracts/deployments/sandpit/build/contracts/ERC20Detailed.json
  smart-contracts/deployments/sandpit/build/contracts/ERC20Mintable.json
  smart-contracts/deployments/sandpit/build/contracts/ERC20UNSAFE.json
  smart-contracts/deployments/sandpit/build/contracts/EthereumBank.json
  smart-contracts/deployments/sandpit/build/contracts/EthereumBankStorage.json
  smart-contracts/deployments/sandpit/build/contracts/EthereumWhiteList.json
  smart-contracts/deployments/sandpit/build/contracts/IERC20.json
  smart-contracts/deployments/sandpit/build/contracts/Migrations.json
  smart-contracts/deployments/sandpit/build/contracts/MinterRole.json
  smart-contracts/deployments/sandpit/build/contracts/MockCosmosBridgeUpgrade.json
  smart-contracts/deployments/sandpit/build/contracts/Oracle.json
  smart-contracts/deployments/sandpit/build/contracts/OracleStorage.json
  smart-contracts/deployments/sandpit/build/contracts/Pausable.json
  smart-contracts/deployments/sandpit/build/contracts/PauserRole.json
  smart-contracts/deployments/sandpit/build/contracts/Roles.json
  smart-contracts/deployments/sandpit/build/contracts/SafeERC20.json
  smart-contracts/deployments/sandpit/build/contracts/SafeMath.json
  smart-contracts/deployments/sandpit/build/contracts/ToLower.json
  smart-contracts/deployments/sandpit/build/contracts/Valset.json
  smart-contracts/deployments/sandpit/build/contracts/ValsetStorage.json
Labels: Ready for Review

#590 [ChainOps] Doc fixes.
  docs/chainOps/k8s.md
Labels: Ready for Review
