Repository Sifchain/sifnode, pull requests merged in 2021-05, with the labels that each got.

#1242 [ChainOps] Cryptoeconomics endpoint helm chart.
  deploy/helm/cryptoeconomics/.gitignore
  deploy/helm/cryptoeconomics/.helmignore
  deploy/helm/cryptoeconomics/Chart.yaml
  deploy/helm/cryptoeconomics/templates/NOTES.txt
  deploy/helm/cryptoeconomics/templates/_helpers.tpl
  deploy/helm/cryptoeconomics/templates/deployment.yaml
  deploy/helm/cryptoeconomics/templates/ingress.yaml
  deploy/helm/cryptoeconomics/templates/role.yaml
  deploy/helm/cryptoeconomics/templates/rolebinding.yaml
  deploy/helm/cryptoeconomics/templates/service.yaml
  deploy/helm/cryptoeconomics/templates/serviceaccount.yaml
  deploy/helm/cryptoeconomics/values.yaml
Labels: Ready for Review

#1243 Adding binance
  deploy/helm/binance/.helmignore
  deploy/helm/binance/Dockerfile
  deploy/helm/binance/template.Chart.yaml
  deploy/helm/binance/template.values.yaml
  deploy/helm/binance/templates/NOTES.txt
  deploy/helm/binance/templates/_helpers.tpl
  deploy/helm/binance/templates/template.deployment.yaml
  deploy/helm/binance/templates/template.ingress.yaml
  deploy/helm/binance/templates/template.pvc.yml
  deploy/helm/binance/templates/template.serviceaccount.yaml
  deploy/rake/cluster.rake
Labels: Ready for Review

#1249 [ChainOps] Cryptoeconomics container resource tweaks.
  deploy/helm/cryptoeconomics/values.yaml
Labels: Ready for Review

#1225 [ChainOps] IBC TestNet contracts.
  smart-contracts/deployments/sifchain-ibctestnet/.openzeppelin/ropsten.json
  smart-contracts/deployments/sifchain-ibctestnet/BridgeBank.json
  smart-contracts/deployments/sifchain-ibctestnet/BridgeRegistry.json
  smart-contracts/deployments/sifchain-ibctestnet/BridgeToken.json
  smart-contracts/deployments/sifchain-ibctestnet/CosmosBridge.json
  smart-contracts/deployments/sifchain-ibctestnet/Migrations.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/Address.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/BankStorage.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/BridgeBank.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/BridgeRegistry.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/BridgeToken.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/Context.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/CosmosBank.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/CosmosBankStorage.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/CosmosBridge.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/CosmosBridgeStorage.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/CosmosWhiteList.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/CosmosWhiteListStorage.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/ERC20.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/ERC20Burnable.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/ERC20Detailed.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/ERC20Mintable.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/ERC20UNSAFE.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/EthereumBank.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/EthereumBankStorage.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/EthereumWhiteList.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/IERC20.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/Migrations.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/MinterRole.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/MockCosmosBridgeUpgrade.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/Oracle.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/OracleStorage.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/Pausable.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/PauserRole.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/Roles.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/SafeERC20.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/SafeMath.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/SifchainTestToken.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/ToLower.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/Valset.json
  smart-contracts/deployments/sifchain-ibctestnet/build/contracts/ValsetStorage.json
Labels: Ready for Review

#1238 Remove duplicate code and deprecated structs in clp querier
  x/clp/keeper/grpc_query.go
  x/clp/keeper/querier.go
  x/clp/keeper/querier_test.go
  x/clp/types/types.go
Labels: cosmos-0.42

#1271 [ChainOps] Version bump.
  version
Labels: Ready for Review

#1267 The integration tests assumed that eth would be in the log of things …
  test/integration/environment_setup.sh
  test/integration/src/py/test_utilities.py
Labels: Ready for Review

#1289 ebrelayer fixes to move eth => ceth for 0.42
  .gitignore
  cmd/ebrelayer/main.go
  cmd/ebrelayer/relayer/cosmos.go
  cmd/ebrelayer/relayer/ethereum.go
  cmd/ebrelayer/replay.go
  cmd/ebrelayer/txs/parser.go
  cmd/ebrelayer/txs/parser_test.go
  cmd/ebrelayer/txs/relayToCosmos.go
  cmd/ebrelayer/txs/relayToEthereum.go
  cmd/sifnoded/cmd/gentx.go
  cmd/sifnoded/cmd/oracle.go
  proto/sifnode/clp/v1/genesis.proto
  proto/sifnode/clp/v1/params.proto
  proto/sifnode/clp/v1/querier.proto
  proto/sifnode/clp/v1/tx.proto
  proto/sifnode/clp/v1/types.proto
  proto/sifnode/dispensation/v1/query.proto
  proto/sifnode/dispensation/v1/tx.proto
  proto/sifnode/dispensation/v1/types.proto
  proto/sifnode/ethbridge/v1/types.proto
  scripts/protocgen.sh
  test/integration/environment_setup.sh
  test/integration/execute_integration_tests_against_test_chain.sh
  test/integration/setup_sifchain.sh
  test/integration/sifchain_run_ebrelayer.sh
  test/integration/src/py/fail_test_ebrelayer_restart.py
  test/integration/src/py/fail_test_liquidity_pools.py
  test/integration/src/py/fail_test_peggy_fees.py
  test/integration/src/py/test_ebrelayer_replay.py
  test/integration/src/py/test_utilities.py
  x/clp/client/cli/tx.go
  x/clp/keeper/grpc_query.go
  x/clp/types/errors.go
  x/clp/types/genesis.pb.go
  x/clp/types/params.pb.go
  x/clp/types/querier.pb.go
  x/clp/types/tx.pb.go
  x/clp/types/types.pb.go
  x/dispensation/client/cli/tx.go
  x/ethbridge/client/cli/tx.go
  x/ethbridge/keeper/querier_test.go
  x/ethbridge/types/msgs.go
  x/ethbridge/types/types.pb.go
  x/oracle/genesis.go
  x/oracle/keeper/keeper.go
Labels: cosmos-0.42, in progress

#1366 Cosmos 42 restore ebrelayer's replay functions
  cmd/ebrelayer/main.go
  cmd/ebrelayer/relayer/cosmos.go
  cmd/ebrelayer/relayer/cosmos_test.go
  cmd/ebrelayer/relayer/ethereum.go
  cmd/ebrelayer/replay.go
  deploy/helm/ebrelayer/templates/deployment.yaml
  test/integration/execute_integration_tests_against_test_chain.sh
  test/integration/sifchain_run_ebrelayer.sh
  test/integration/src/py/test_ebrelayer_replay.py
Labels: cosmos-0.42

#1399 Prepare for ui extraction pt I
  .github/workflows/ui-stack.yml
  ui/scripts/build-stack-backend-docker.sh
  ui/scripts/latest
  ui/scripts/run-stack-backend-from-scratch.sh
  ui/scripts/run-stack-save-default-snapshot.sh
Labels: Ready for Review

#1403 Fixed issues with ebrelayer tests caused by 42 timing changes and fixed issues from a merge of the ebrelayer retry work
  cmd/ebrelayer/main.go
  cmd/ebrelayer/relayer/cosmos.go
  cmd/ebrelayer/relayer/cosmos_test.go
  cmd/ebrelayer/replay.go
  test/integration/execute_integration_tests_against_test_chain.sh
  test/integration/sifchain_start_ebrelayer.sh
  test/integration/src/py/test_ebrelayer_restart.py
Labels: cosmos-0.42
