Repository Sifchain/sifnode, pull requests merged in 2021-03, with the labels that each got.

#862 [ui] app/Panel.vue: hide scroll bar always
  ui/app/src/components/shared/Panel.vue
Labels: Ready for Review, frontend

#871 [ChainOps] Doc tweaks/cleanup.
  deploy/docker/mainnet/docker-compose.yml
  deploy/docker/mainnet/entrypoint.sh
  deploy/rake/genesis.rake
  docs/chainOps/k8s/README.md
  docs/chainOps/k8s/tutorials/betanet.md
  docs/chainOps/standalone/tutorials/betanet.md
Labels: Ready for Review

#869 [ChainOps] Support for DataDog.
  deploy/helm/datadog/values.yaml
Labels: Ready for Review

#870 [ChainOps] Release 20210301075600.
  app/app.go
Labels: Ready for Review

#782 [ui] fix for making back button work on pooling in different states
  ui/app/src/views/CreatePoolPage.vue
Labels: frontend

#860 [UI] Fix pool stats
  ui/app/src/components/poolStats/PoolStatsListHeader.vue
Labels: frontend

#876 [ChainOps] Testnet updates.
  deploy/docker/mainnet/docker-compose.yml
  deploy/docker/scripts/entrypoint.sh
  deploy/docker/testnet/docker-compose.yml
  deploy/rake/genesis.rake
  docs/chainOps/k8s/tutorials/betanet.md
  docs/chainOps/k8s/tutorials/testnet.md
  docs/chainOps/standalone/tutorials/betanet.md
  docs/chainOps/standalone/tutorials/testnet.md
Labels: Ready for Review

#907 [ChainOps] Setup Pools/LPs at genesis.
  cmd/sifgen/main.go
  deploy/helm/sifnode/templates/deployment.yaml
  deploy/helm/sifnode/values.yaml
  deploy/rake/cluster.rake
  tools/sifgen/common/types/genesis.go
  tools/sifgen/genesis/genesis.go
  tools/sifgen/node/node.go
Labels: Ready for Review

#905 [ChainOps] RPC Updates.
  deploy/docker/mainnet/docker-compose.yml
  deploy/helm/sifnode/templates/NOTES.txt
  deploy/helm/sifnode/templates/deployment.yaml
  deploy/helm/sifnode/templates/service.yaml
  deploy/helm/sifnode/values.yaml
Labels: Ready for Review

#865 Improve wallets behavior
  ui/app/src/App.vue
  ui/app/src/assets/keplr.jpg
  ui/app/src/assets/metamask.png
  ui/app/src/components/actionsPanel/ActionsPanel.vue
  ui/app/src/components/shared/SifButton.vue
  ui/app/src/components/wallet/BalanceTable.vue
  ui/app/src/components/wallet/EtheriumWalletPanel.vue
  ui/app/src/components/wallet/KeplrWalletPanel.vue
  ui/app/src/components/wallet/WithWallet.vue
  ui/app/src/components/wallet/useWalletButton.ts
  ui/app/src/views/CreatePoolPage.vue
  ui/app/src/views/RemoveLiquidityPage.vue
  ui/app/src/views/SwapPage.vue
  ui/core/src/actions/ethWallet.test.ts
  ui/core/src/actions/wallet.ts
  ui/core/src/api/EthereumService/EthereumService.test.ts
  ui/core/src/api/EthereumService/EthereumService.ts
  ui/core/src/api/SifService/SifService.ts
  ui/core/src/api/SifService/getKeplrProvider.ts
Labels: frontend

#840 [ui] Feature/cross session peg notification
  ui/app/src/App.vue
  ui/app/src/components/shared/AssetList.vue
  ui/app/src/components/shared/Icon.vue
  ui/app/src/components/shared/Tooltip.vue
  ui/app/src/hooks/useInitialize.ts
  ui/app/src/hooks/useSubscrition.ts
  ui/app/src/views/PegListingPage.vue
  ui/app/src/views/utils/toConfirmState.ts
  ui/core/src/actions/peg/index.ts
  ui/core/src/actions/peg/subscribeToUnconfirmedPegTxs.ts
  ui/core/src/actions/peg/utils/subscribeToTx.ts
  ui/core/src/api/EthbridgeService/EthbridgeService.ts
  ui/core/src/api/EthbridgeService/PegTxEventEmitter.ts
  ui/core/src/api/EthbridgeService/types.ts
  ui/core/src/api/EthbridgeService/utils/confirmTx.ts
  ui/core/src/entities/Transaction.ts
  ui/core/src/store/index.ts
  ui/core/src/store/tx.ts
Labels: frontend

#923 [ChainOps] Updated peer addresses.
  deploy/docker/testnet/docker-compose.yml
  docs/chainOps/k8s/tutorials/testnet.md
  docs/chainOps/standalone/tutorials/testnet.md
Labels: Ready for Review

#915 [ChainOps] RPC Rollback.
  deploy/docker/mainnet/docker-compose.yml
  deploy/helm/sifnode/templates/deployment.yaml
  deploy/helm/sifnode/templates/service.yaml
  deploy/helm/sifnode/values.yaml
Labels: Ready for Review

#931 [ChainOps] State export
  app/app.go
Labels: Ready for Review

#926 [ui] app/poolstatslistitem: pool apy * 100
  ui/app/src/components/poolStats/PoolStatsListItem.vue
Labels: frontend

#892 [ui] EventBusService
  ui/app/src/components/Notifications.vue
  ui/core/src/actions/clp/index.ts
  ui/core/src/actions/ethWallet.test.ts
  ui/core/src/actions/ethWallet.ts
  ui/core/src/actions/peg/index.ts
  ui/core/src/actions/peg/subscribeToUnconfirmedPegTxs.ts
  ui/core/src/actions/peg/utils/subscribeToTx.ts
  ui/core/src/actions/wallet.ts
  ui/core/src/api/EthereumService/EthereumService.ts
  ui/core/src/api/EthereumService/utils/getMetamaskProvider.ts
  ui/core/src/api/EventBusService/EventBusService.ts
  ui/core/src/api/EventBusService/Events.ts
  ui/core/src/api/EventBusService/index.ts
  ui/core/src/api/IWalletService.ts
  ui/core/src/api/index.ts
  ui/core/src/api/utils/Notifications.ts
  ui/core/src/entities/Notifications.ts
  ui/core/src/entities/index.ts
  ui/core/src/store/index.ts
  ui/core/src/store/notifications.ts
  ui/core/src/test/utils/getMockWalletService.ts
Labels: Front End

#896 [ui] showing a warning during pooling
  ui/app/src/components/shared/FatInfoTable.vue
  ui/app/src/components/shared/Icon.vue
  ui/app/src/components/shared/icons/Exclaimation.vue
  ui/app/src/views/CreatePoolPage.vue
  ui/core/src/entities/formulae.ts
  ui/core/src/hooks/addLiquidityCalculator.ts
Labels: frontend

#868 [peggy] structured logging
  cmd/ebrelayer/main.go
  cmd/ebrelayer/relayer/cosmos.go
  cmd/ebrelayer/relayer/cosmos_test.go
  cmd/ebrelayer/relayer/ethereum.go
  cmd/ebrelayer/relayer/listMissedEvent.go
  cmd/ebrelayer/replay.go
  cmd/ebrelayer/txs/parser.go
  cmd/ebrelayer/txs/parser_test.go
  cmd/ebrelayer/txs/registry.go
  cmd/ebrelayer/txs/relayToCosmos.go
  cmd/ebrelayer/txs/relayToEthereum.go
  cmd/ebrelayer/types/events.go
  go.mod
  go.sum
  x/ethbridge/handler.go
  x/ethbridge/keeper/keeper.go
  x/ethbridge/keeper/keeper_test.go
  x/ethbridge/keeper/querier_test.go
  x/ethbridge/types/expected_keepers.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/keeper_test.go
Labels: Peggy

#663 [ui] guided liquidity pool calculations
  ui/app/src/components/currencyPairPanel/Index.vue
  ui/app/src/components/currencyfield/CurrencyField.vue
  ui/app/src/components/shared/Checkbox.vue
  ui/app/src/components/shared/RaisedPanel.vue
  ui/app/src/components/shared/RaisedPanelRow.vue
  ui/app/src/views/CreatePoolPage.vue
  ui/core/src/hooks/addLiquidityCalculator.test.ts
  ui/core/src/hooks/addLiquidityCalculator.ts
Labels: frontend

#945 Add scripts to mint and distribute tokens on sandpit
  smart-contracts/package.json
  smart-contracts/scripts/test/contractUtilities.js
  smart-contracts/scripts/test/mintTestnetErowan.js
  smart-contracts/scripts/test/mintTestnetTokens.js
  smart-contracts/scripts/test/sendBurnTx.js
  smart-contracts/scripts/test/sendLockTx.js
  smart-contracts/scripts/test/sifchainUtilities.js
  smart-contracts/scripts/test/updateAddresses.js
  smart-contracts/scripts/test/whitelistedTokens.js
  test/integration/README.md
  test/integration/distribute_tokens.sh
  test/integration/environment_setup.sh
  test/integration/src/py/conftest.py
  test/integration/src/py/test_eth_transfers.py
  test/integration/src/py/test_liquidity_pools.py
  test/integration/src/py/test_utilities.py
  test/integration/src/py/token_distribution.py
  test/integration/src/py/token_refresh.py
Labels: Ready for Review

#799 [ChainOps] Set CHAINNET correctly on release builds.
  Makefile
  cmd/sifnodecli/Dockerfile
  cmd/sifnoded/Dockerfile
  deploy/release/release.sh
Labels: Ready for Review, bug

#933 Integration tests should not use hardcoded paths
  test/integration/environment_setup.sh
Labels: Ready for Review

#969 [ChainOps] Explorer Tokens
  deploy/helm/block-explorer/templates/configmap.yaml
Labels: ChainOps, blockExplorer

#972 [ChainOps] Volume snapshot role/policy tweaks
  deploy/terraform/providers/aws/volumes.tf
Labels: ChainOps, Ready for Review

#671 [Peggy] Cosmos Per Block Solution
  cmd/ebrelayer/main.go
  cmd/ebrelayer/relayer/cosmos.go
  cmd/ebrelayer/relayer/cosmos_test.go
  cmd/ebrelayer/relayer/ethereum.go
  cmd/ebrelayer/replay.go
  test/integration/src/py/test_ebrelayer_restart.py
  test/integration/src/py/test_utilities.py
Labels: onhold

#694 [peggy] retry if any error from process block
  cmd/ebrelayer/relayer/ethereum.go
Labels: Under Review

#885 [ui] Amount API Proposal
  ui/docs/decisions/adr-amount.md
  ui/docs/decisions/adr-display.md
Labels: frontend

#981 Documentation updates
  smart-contracts/LimitUpdating.md
Labels: Ready for Review

#879 [Peggy Docs] Whitelisting Docs Update
  smart-contracts/LimitUpdating.md
  smart-contracts/ProdEnvRunbook.md
  smart-contracts/data/limitWhitelistUpdate.json
Labels: Peggy

#1001 [ChainOps] New release.
  app/app.go
Labels: Ready for Review

#997 [ChainOps] Terraform Fixes.
  deploy/helm/sifnode/templates/deployment.yaml
  deploy/helm/sifnode/values.yaml
  deploy/rake/cluster.rake
  deploy/terraform/providers/aws/cluster_autoscaler.tf
  deploy/terraform/providers/aws/main.tf
  deploy/terraform/providers/aws/variables.tf
Labels: Ready for Review

#1004 [ChainOps] TestNet documentation.
  deploy/docker/testnet/docker-compose.yml
  docs/chainOps/k8s/tutorials/testnet.md
  docs/chainOps/standalone/tutorials/testnet.md
Labels: Ready for Review

#976 [ui] Add coverage to prettier ignore
  ui/.prettierignore
Labels: Front End

#1009 [testnet-hotfix][ui] ui/core: testnet, devnet chainId (semi) fix
  ui/core/src/config.devnet.json
  ui/core/src/config.testnet.json
Labels: ChainOps, High

#1007 [ChainOps] TF Config.
  deploy/terraform/providers/aws/main.tf
  deploy/terraform/providers/aws/variables.tf
Labels: Ready for Review

#1045 [ChainOps] Workflow tweaks
  .github/workflows/release.yml
Labels: Ready for Review

#1046 [ChainOps] TestNet documentation
  deploy/docker/scripts/entrypoint.sh
  deploy/docker/testnet/docker-compose.yml
  docs/chainOps/k8s/tutorials/testnet.md
  docs/chainOps/standalone/tutorials/testnet.md
Labels: Ready for Review

#1049 Add sif address for the user-run faucet
  test/integration/distribute_tokens.sh
Labels: Ready for Review
