Repository Sifchain/sifnode, pull requests merged in 2021-04, with the labels that each got.

#959 [peggy] Account for ceth transfer
  app/app.go
  docs/peggy/Peggy-Ceth-Account-Set.md
  scripts/get-ethbridge-ceth.sh
  test/integration/sifchain_start_daemon.sh
  test/integration/src/py/conftest.py
  test/integration/src/py/integration_env_credentials.py
  test/integration/src/py/pytest_utilities.py
  test/integration/src/py/test_peggy_fees.py
  test/integration/src/py/test_utilities.py
  x/ethbridge/alias.go
  x/ethbridge/client/cli/tx.go
  x/ethbridge/client/module_client.go
  x/ethbridge/handler.go
  x/ethbridge/handler_test.go
  x/ethbridge/keeper/cethReceiverAccount.go
  x/ethbridge/keeper/cethReceiverAccount_test.go
  x/ethbridge/keeper/keeper.go
  x/ethbridge/keeper/keeper_test.go
  x/ethbridge/keeper/test_common.go
  x/ethbridge/test_common.go
  x/ethbridge/types/codec.go
  x/ethbridge/types/events.go
  x/ethbridge/types/expected_keepers.go
  x/ethbridge/types/keys.go
  x/ethbridge/types/msgs.go
  x/ethbridge/types/test_common.go
  x/oracle/keeper/adminAccount.go
  x/oracle/keeper/adminAccount_test.go
Labels: Peggy

#1061 [ui] Updated contract addresses.
  ui/core/src/config.devnet.json
  ui/core/src/config.testnet.json
Labels: Ready for Review

#1012 app: merge binaries & clean app.go
  Makefile
  app/app.go
  app/app_test.go
  app/encoding.go
  app/export.go
  app/genesis.go
  cmd/sifnodecli/Dockerfile
  cmd/sifnodecli/main.go
  cmd/sifnoded/cmd/clpadmin.go
  cmd/sifnoded/cmd/faucet.go
  cmd/sifnoded/cmd/genaccounts.go
  cmd/sifnoded/cmd/gentx.go
  cmd/sifnoded/cmd/oracle.go
  cmd/sifnoded/cmd/root.go
  cmd/sifnoded/genaccounts.go
  cmd/sifnoded/main.go
  go.mod
  go.sum
  tools/sifgen/common/common.go
  tools/sifgen/key/key.go
  tools/sifgen/network/network.go
  tools/sifgen/node/node.go
  tools/sifgen/utils/cli.go
  x/clp/types/genesis.go
  x/oracle/types/genesis.go
Labels: go

#1076 Truffle update requires no sudo for install
  test/integration/setup-linux-environment-user.sh
Labels: Ready for Review

#1078 Improve rescue ceth tests
  test/integration/src/py/conftest.py
  test/integration/src/py/test_peggy_fees.py
Labels: Ready for Review

#1077 PR 1044 made it impossible to start without a whitelist, adjust tests
  test/integration/execute_integration_tests_against_test_chain.sh
  test/integration/sifchain_start_daemon.sh
  test/integration/src/py/conftest.py
  test/integration/src/py/test_no_whitelisted_validators.py
  test/integration/start-integration-env.sh
Labels: Ready for Review

#1016 proto: orcale module split out
  app/app.go
  app/test_helpers.go
  cmd/sifnoded/cmd/gentx.go
  cmd/sifnoded/cmd/oracle.go
  go.mod
  proto/sifnode/oracle/v1/types.proto
  x/oracle/alias.go
  x/oracle/genesis.go
  x/oracle/keeper/adminAccount.go
  x/oracle/keeper/adminAccount_test.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/keeper_test.go
  x/oracle/keeper/test_common.go
  x/oracle/keeper/validatorWhiteList.go
  x/oracle/keeper/validatorWhiteList_test.go
  x/oracle/module.go
  x/oracle/types/claim.go
  x/oracle/types/codec.go
  x/oracle/types/expected_keepers.go
  x/oracle/types/genesis.go
  x/oracle/types/prophecy.go
  x/oracle/types/status.go
  x/oracle/types/types.pb.go
Labels: go

#1084 [ChainOps] Explorer updates
  deploy/helm/block-explorer/Chart.yaml
  deploy/helm/block-explorer/templates/deployment.yaml
  deploy/helm/block-explorer/values.yaml
  deploy/helm/mongodb/values.yaml
  deploy/rake/cluster.rake
Labels: ChainOps, Ready for Review

#1086 [ChainOps] Explorer bugfix.
  deploy/helm/block-explorer/templates/configmap.yaml
Labels: ChainOps, Ready for Review

#1027 Feature/multi sig
  app/app.go
  app/app_test.go
  app/export.go
  app/poolChange.go
  app/release-20210501000000-AddDispensation.go
  app/setupHandlers.go
  go.mod
  scripts/demos/dispensation/airdrop.sh
  scripts/demos/dispensation/queries.sh
  scripts/init-upgrade.sh
  scripts/init.sh
  scripts/upgrade.sh
  simapp/app.go
  tools/sifgen/common/types/genesis.go
  tools/sifgen/sifgen.go
  x/clp/client/cli/query.go
  x/clp/client/cli/tx.go
  x/clp/test/test_common.go
  x/dispensation/README.md
  x/dispensation/abci.go
  x/dispensation/alias.go
  x/dispensation/client/cli/query.go
  x/dispensation/client/cli/tx.go
  x/dispensation/genesis.go
  x/dispensation/handler.go
  x/dispensation/handler_test.go
  x/dispensation/keeper/distribution.go
  x/dispensation/keeper/distributionRecords.go
  x/dispensation/keeper/executors.go
  x/dispensation/keeper/executors_test.go
  x/dispensation/keeper/keeper.go
  x/dispensation/keeper/keeper_test.go
  x/dispensation/keeper/querier.go
  x/dispensation/keeper/querier_test.go
  x/dispensation/module.go
  x/dispensation/test/test_common.go
  x/dispensation/types/codec.go
  x/dispensation/types/errors.go
  x/dispensation/types/events.go
  x/dispensation/types/expected_keepers.go
  x/dispensation/types/genesis.go
  x/dispensation/types/keys.go
  x/dispensation/types/msgs.go
  x/dispensation/types/querier.go
  x/dispensation/types/records.go
  x/dispensation/types/types.go
  x/dispensation/utils/parser.go
  x/dispensation/utils/parser_test.go
  x/dispensation/utils/verfifysigner.go
Labels: Ready for Review, in progress

#1129 [ChainOps] Param changes.
  app/app.go
  app/setupHandlers.go
Labels: Ready for Review

#1126 Integration tests for the ceth rescue account
  test/integration/src/py/conftest.py
  test/integration/src/py/test_peggy_fees.py
Labels: Ready for Review

#1150 Faucetrandomcurrency
  test/integration/.gitignore
  test/integration/src/py/test_liquidity_pools.py
Labels: Testing

#1051 Token distribution for test deployments should also set the ceth limit
  test/integration/distribute_tokens.sh
  test/integration/src/py/token_setup.py
Labels: Ready for Review

#1164 Remove balance restriction
  ui/app/src/components/tokenSelector/SelectTokenDialogSif.vue
Labels: Front End, Ready for Review

#1163 Fix decimal places in listing
  ui/app/src/components/shared/utils.ts
Labels: Front End, Ready for Review

#1169 [ChainOps] Set the address prefix.
  app/app.go
  cmd/sifnoded/main.go
Labels: Ready for Review

#1155 export ethbridge keeper data to genesis.
  docs/peggy/Peggy-Export-Data.md
  docs/peggy/genesis.json
  x/ethbridge/genesis.go
  x/ethbridge/module.go
  x/ethbridge/types/genesis.go
  x/oracle/keeper/adminAccount.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/validatorWhiteList.go
  x/oracle/module.go
Labels: Ready for Review

#1174 Add Retry Logic to Relayers
  cmd/ebrelayer/txs/relayToEthereum.go
Labels: Ready for Review

#1162 [ChainOps] MongoDB updates.
  deploy/helm/mongodb/values.yaml
Labels: Ready for Review

#1153 [ChainOps] Treasury runbook.
  docs/chainOps/runbooks/Pay-from-Treasury.md
  payments/payment-20210420
Labels: Ready for Review

#1175 Sifdocker
  .github/workflows/sifdocker.yml
Labels: Testing

#1193 using org token and repo
  .github/workflows/sifdocker.yml
Labels: Testing
