Repository Sifchain/sifnode, pull requests merged in 2021-11, with the labels that each got.

#2116 [ChainOps] Release tweaks
  .github/workflows/release.yml
Labels: Ready for Review

#2133 add unit tests for keeper/calculations
  x/clp/keeper/keeper_test.go
Labels: Sifnode

#2173 Feature | Inflation Rewards
  app/setup_handlers.go
  version
Labels: Sifnode

#2152 store the denom in map for performance
  cmd/ebrelayer/relayer/ethereum.go
  x/ethbridge/keeper/msg_server.go
  x/tokenregistry/keeper/keeper.go
  x/tokenregistry/types/keys.go
Labels: Ready for Review, Peggy 2.0

#2179 fix: integration tests min fees
  test/integration/src/py/test_claims.py
Labels: Sifnode

#2176 Ethereum blacklisting
  proto/sifnode/ethbridge/v1/query.proto
  proto/sifnode/ethbridge/v1/tx.proto
  scripts/init.sh
  x/ethbridge/client/cli/query.go
  x/ethbridge/client/cli/tx.go
  x/ethbridge/client/module_client.go
  x/ethbridge/handler.go
  x/ethbridge/keeper/blacklist.go
  x/ethbridge/keeper/blacklist_test.go
  x/ethbridge/keeper/grpc_query.go
  x/ethbridge/keeper/keeper.go
  x/ethbridge/keeper/msg_server.go
  x/ethbridge/keeper/querier.go
  x/ethbridge/types/codec.go
  x/ethbridge/types/keys.go
  x/ethbridge/types/msgs.go
  x/ethbridge/types/querier.go
  x/ethbridge/types/query.pb.go
  x/ethbridge/types/tx.pb.go
  x/ethbridge/types/types.go
Labels: Sifnode

#2220 feat: script to download ofac list for sifnode
  smart-contracts/scripts/download_ofac_blocklist.js
Labels: Sifnode
