Repository Sifchain/sifnode, pull requests merged in 2021-08, with the labels that each got.

#1736 remove binding command
  cmd/ebrelayer/contract/generator.go
  cmd/ebrelayer/main.go
Labels: Ready for Review, Peggy 2.0

#1782 [ChainOps] Renamed the production deployment.
  smart-contracts/Upgrade.md
  smart-contracts/deployments/sifchain-1/.openzeppelin/mainnet.json
  smart-contracts/deployments/sifchain-1/.openzeppelin/unknown-1337.json
  smart-contracts/deployments/sifchain-1/BridgeBank.json
  smart-contracts/deployments/sifchain-1/BridgeRegistry.json
  smart-contracts/deployments/sifchain-1/CosmosBridge.json
  smart-contracts/deployments/sifchain-1/Migrations.json
  smart-contracts/deployments/sifchain-1/build/contracts/Address.json
  smart-contracts/deployments/sifchain-1/build/contracts/BankStorage.json
  smart-contracts/deployments/sifchain-1/build/contracts/BridgeBank.json
  smart-contracts/deployments/sifchain-1/build/contracts/BridgeRegistry.json
  smart-contracts/deployments/sifchain-1/build/contracts/BridgeToken.json
  smart-contracts/deployments/sifchain-1/build/contracts/Context.json
  smart-contracts/deployments/sifchain-1/build/contracts/CosmosBank.json
  smart-contracts/deployments/sifchain-1/build/contracts/CosmosBankStorage.json
  smart-contracts/deployments/sifchain-1/build/contracts/CosmosBridge.json
  smart-contracts/deployments/sifchain-1/build/contracts/CosmosBridgeStorage.json
  smart-contracts/deployments/sifchain-1/build/contracts/CosmosWhiteList.json
  smart-contracts/deployments/sifchain-1/build/contracts/CosmosWhiteListStorage.json
  smart-contracts/deployments/sifchain-1/build/contracts/ERC20.json
  smart-contracts/deployments/sifchain-1/build/contracts/ERC20Burnable.json
  smart-contracts/deployments/sifchain-1/build/contracts/ERC20Detailed.json
  smart-contracts/deployments/sifchain-1/build/contracts/ERC20Mintable.json
  smart-contracts/deployments/sifchain-1/build/contracts/ERC20UNSAFE.json
  smart-contracts/deployments/sifchain-1/build/contracts/EthereumBank.json
  smart-contracts/deployments/sifchain-1/build/contracts/EthereumBankStorage.json
  smart-contracts/deployments/sifchain-1/build/contracts/EthereumWhiteList.json
  smart-contracts/deployments/sifchain-1/build/contracts/IERC20.json
  smart-contracts/deployments/sifchain-1/build/contracts/Migrations.json
  smart-contracts/deployments/sifchain-1/build/contracts/MinterRole.json
  smart-contracts/deployments/sifchain-1/build/contracts/MockCosmosBridgeUpgrade.json
  smart-contracts/deployments/sifchain-1/build/contracts/Oracle.json
  smart-contracts/deployments/sifchain-1/build/contracts/OracleStorage.json
  smart-contracts/deployments/sifchain-1/build/contracts/Pausable.json
  smart-contracts/deployments/sifchain-1/build/contracts/PauserRole.json
  smart-contracts/deployments/sifchain-1/build/contracts/Roles.json
  smart-contracts/deployments/sifchain-1/build/contracts/SafeERC20.json
  smart-contracts/deployments/sifchain-1/build/contracts/SafeMath.json
  smart-contracts/deployments/sifchain-1/build/contracts/ToLower.json
  smart-contracts/deployments/sifchain-1/build/contracts/Valset.json
  smart-contracts/deployments/sifchain-1/build/contracts/ValsetStorage.json
Labels: Ready for Review

#1779 Add Post IBC Whitelist Update
  smart-contracts/data/whitelist_mainnet_update_postibc.json
Labels: Sifnode

#1775 ethereum lock burn nonce support
  proto/sifnode/ethbridge/v1/types.proto
  x/ethbridge/keeper/ethereumLockBurnNonce.go
  x/ethbridge/keeper/ethereumLockBurnNonce_test.go
  x/ethbridge/keeper/msg_server.go
  x/ethbridge/types/keys.go
  x/ethbridge/types/types.pb.go
Labels: Ready for Review
