Repository Sifchain/sifnode, pull requests merged in 2021-06, with the labels that each got.

#1371 Test add-genesis-validator cmd
  cmd/sifnoded/cmd/add_genesis_validator_test.go
Labels: cosmos-0.42

#1377 [ChainOps] Release v0.8.5.
  CHANGELOG.md
  app/setupHandlers.go
  version
Labels: in progress

#1454 ebrelayer meeting changes
  cmd/ebrelayer/txs/parser.go
  cmd/ebrelayer/txs/parser_test.go
  proto/sifnode/ethbridge/v1/types.proto
  x/ethbridge/types/types.pb.go
Labels: Ready for Review, cosmos-0.42

#1393 Feature/test liquidity pools fix
  cmd/ebrelayer/relayer/ethereum.go
  test/integration/execute_integration_tests_against_test_chain.sh
  test/integration/src/py/test_liquidity_pools.py
  x/clp/client/cli/tx.go
  x/clp/keeper/querier_test.go
  x/dispensation/keeper/grpc_querier.go
Labels: Ready for Review

#1444 fix typo
  docs/clp/clp-adr.md
  x/clp/README.md
  x/clp/types/types.go
Labels: Ready for Review, Sifnode

#1475 Remove obsolete tests for 42
  test/integration/src/py/test_new_currency_transfers.py
Labels: cosmos-0.42

#855 add empty pool case for calcPoolUnits - arch doc
  docs/clp/Liquidity Pools Architecture.md
Labels: Ready for Review, documentation

#1435 Added potential protobuf file for network descriptors
  proto/sifnode/oracle/v1/network_descriptor.proto
  x/oracle/types/network_descriptor.pb.go
Labels: Peggy, cosmos-0.42
