Repository Sifchain/sifnode, pull requests merged in 2021-10, with the labels that each got.

#1850 Add whitelist script using new hardhat functions
  smart-contracts/scripts/whitelist.ts
  smart-contracts/src/whitelist.ts
  smart-contracts/test/test_newBridgeBank.ts
  smart-contracts/tsconfig.json
Labels: Peggy

#1851 Clean up some script setup code for hardhat
  smart-contracts/scripts/bulk_set_whitelist.ts
  smart-contracts/scripts/whitelist.ts
  smart-contracts/src/hardhatFunctions.ts
  smart-contracts/tsconfig.json
Labels: Peggy

#2070 Add new registry entries
  scripts/ibc/tokenregistration/envs/testnet.sh
  scripts/ibc/tokenregistration/generate-ibc-jsons.sh
  scripts/ibc/tokenregistration/sifchain-testnet-1/band.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/bitsong.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/likecoin.json
Labels: Sifnode

#2107 [ChainOps] Peggy Logging
  cmd/ebrelayer/relayer/cosmos.go
Labels: Ready for Review
