Repository Sifchain/sifnode, pull requests merged in 2022-09, with the labels that each got.

#3184 Add admin close and tests
  proto/sifnode/margin/v1/tx.proto
  x/clp/types/pool_FEATURE_TOGGLE_MARGIN_CLI_ALPHA.pb.go
  x/margin/client/cli/admin_tx.go
  x/margin/client/cli/tx.go
  x/margin/keeper/abci.go
  x/margin/keeper/admin_msg_server.go
  x/margin/keeper/admin_msg_server_test.go
  x/margin/keeper/events.go
  x/margin/keeper/keeper.go
  x/margin/keeper/legacy.go
  x/margin/keeper/msg_server.go
  x/margin/types/codec.go
  x/margin/types/events.go
  x/margin/types/expected_keepers.go
  x/margin/types/msgs.go
  x/margin/types/tx.pb.go
Labels: draft

#3221 remove ErrcrossChainFee
  x/ethbridge/types/errors.go
Labels: Peggy Team

#3179 register MsgRegisterAll and MsgDeregisterAll
  x/tokenregistry/handler/handler.go
Labels: Peggy Team

#3177 remove redundant check
  x/ethbridge/keeper/keeper.go
Labels: Peggy Team

#3219 add validate for blacklist
  x/ethbridge/types/msgs.go
  x/ethbridge/types/msgs_test.go
Labels: Peggy Team

#3176 fix wrong encode method
  cmd/ebrelayer/txs/signature.go
  cmd/ebrelayer/txs/test_common.go
Labels: Peggy Team

#3230 remove duplicate error check
  x/tokenregistry/client/cli/tx.go
  x/tokenregistry/keeper/grpc_query.go
Labels: Peggy Team

#3241 remove duplicate attribute
  x/ethbridge/types/events.go
  x/oracle/keeper/keeper.go
  x/oracle/types/events.go
Labels: Peggy Team

#3160 fix oracle genesis data
  proto/sifnode/oracle/v1/types.proto
  x/oracle/genesis.go
  x/oracle/genesis_test.go
  x/oracle/keeper/consensusNeeded.go
  x/oracle/keeper/crossChainFee.go
  x/oracle/keeper/prophecy.go
  x/oracle/keeper/witnessLockBurnNonce.go
  x/oracle/types/crossChainFeeConfig.go
  x/oracle/types/types.pb.go
Labels: Peggy Team

#3269 lint depends on generating the protobuf files, fixed the makefile
  Makefile
  x/oracle/types/crossChainFeeConfig.go
Labels: Peggy Team, Peggy 2.0

#2748 Move NetworkIdentity into protobuf
  proto/sifnode/oracle/v1/network_descriptor.proto
  proto/sifnode/oracle/v1/types.proto
  x/ethbridge/keeper/ethereumLockBurnSequence.go
  x/ethbridge/keeper/globalNonce.go
  x/oracle/keeper/consensusNeeded.go
  x/oracle/keeper/crossChainFee.go
  x/oracle/keeper/prophecy.go
  x/oracle/keeper/validatorWhiteList.go
  x/oracle/keeper/witnessLockBurnNonce.go
  x/oracle/keeper/witnessLockBurnNonce_test.go
  x/oracle/types/networkIdentity.go
  x/oracle/types/networkIdentity_test.go
  x/oracle/types/network_descriptor.pb.go
  x/oracle/types/types.pb.go
Labels: Peggy Team

#3246 Merge master to peggy2
  app/app.go
  app/setup_handlers.go
  scripts/clp/add.sh
  scripts/clp/lppd-params.json
  scripts/clp/lppd-params.sh
  scripts/clp/remove.sh
  scripts/clp/reward-params.sh
  scripts/clp/reward-period.json
  scripts/clp/reward-period.sh
  x/clp/abci.go
  x/clp/abci_test.go
  x/clp/handler_test.go
  x/clp/keeper/calculations.go
  x/clp/keeper/calculations_test.go
  x/clp/keeper/executors.go
  x/clp/keeper/invariants.go
  x/clp/keeper/invariants_test.go
  x/clp/keeper/msg_server.go
  x/clp/keeper/msg_server_test.go
  x/clp/keeper/pmtp.go
  x/clp/keeper/rewards.go
  x/clp/keeper/rewards_test.go
  x/clp/module.go
  x/clp/test/test_common.go
  x/clp/types/errors.go
  x/clp/types/types.go
  x/margin/keeper/abci.go
  x/margin/keeper/keeper.go
  x/margin/keeper/msg_server.go
  x/margin/keeper/msg_server_test.go
  x/margin/types/expected_keepers.go
Labels: Peggy Team, Peggy 2.0
