Repository Sifchain/sifnode, pull requests merged in 2022-05, with the labels that each got.

#2705 [ChainOps] Workflow updates
  .github/workflows/peggy-docs.yml
  .github/workflows/release.yml
Labels: Ready for Review

#2773 LP Upgrade Handler
  x/clp/keeper/migrations.go
  x/clp/module.go
Labels: draft

#2778 Fix unit test for smart contract
  smart-contracts/contracts/CosmosBridge.sol
  smart-contracts/test/helpers/testFixture.js
  smart-contracts/test/testCosmosBridge.js
  smart-contracts/test/testSignatureAggregationSecurity.js
Labels: Peggy Team

#2752 Remove whitelist flag in metadata
  proto/sifnode/tokenregistry/v1/types.proto
  smart-contracts/src/devenv/registry.json
  test/integration/whitelisted-denoms.json
  x/ethbridge/handler_test.go
  x/tokenregistry/keeper/metadata.go
  x/tokenregistry/keeper/metadata_test.go
  x/tokenregistry/types/types.pb.go
Labels: Peggy Team

#2726 store both BridgeBank and CosmosBridge addresses
  cmd/ebrelayer/txs/registry.go
Labels: Peggy Team
