Repository Sifchain/sifnode, pull requests merged in 2022-04, with the labels that each got.

#2582 Upgrade Handler + Migrator for PMTP
  app/setup_handlers.go
  proto/sifnode/clp/v1/types.proto
  x/clp/keeper/migrations.go
  x/clp/module.go
  x/clp/types/types.pb.go
Labels: in progress, PMTP Team

#2593 Work in progress on smart contract optimizations
  smart-contracts/Makefile
  smart-contracts/Makefile.artifacts
  smart-contracts/Makefile.smartContracts
  smart-contracts/contracts/Blocklist.sol
  smart-contracts/contracts/BridgeBank/BankStorage.sol
  smart-contracts/contracts/BridgeBank/BridgeBank.sol
  smart-contracts/contracts/BridgeBank/BridgeToken.sol
  smart-contracts/contracts/BridgeBank/CosmosBank.sol
  smart-contracts/contracts/BridgeBank/CosmosBankStorage.sol
  smart-contracts/contracts/BridgeBank/CosmosWhiteList.sol
  smart-contracts/contracts/BridgeBank/CosmosWhiteListStorage.sol
  smart-contracts/contracts/BridgeBank/EthereumBankStorage.sol
  smart-contracts/contracts/BridgeBank/EthereumWhitelist.sol
  smart-contracts/contracts/BridgeBank/Pausable.sol
  smart-contracts/contracts/BridgeBank/PauserRole.sol
  smart-contracts/contracts/BridgeBank/Rowan.sol
  smart-contracts/contracts/BridgeRegistry.sol
  smart-contracts/contracts/CosmosBridge.sol
  smart-contracts/contracts/CosmosBridgeStorage.sol
  smart-contracts/contracts/Migrations.sol
  smart-contracts/contracts/MockUpgrade/ERC20UNSAFE.sol
  smart-contracts/contracts/MockUpgrade/MockCosmosBridgeUpgrade.sol
  smart-contracts/contracts/Mocks/CommissionToken.sol
  smart-contracts/contracts/Mocks/FailHardToken.sol
  smart-contracts/contracts/Mocks/FakeERC20.sol
  smart-contracts/contracts/Mocks/ManyDecimalsToken.sol
  smart-contracts/contracts/Mocks/RandomTrollToken.sol
  smart-contracts/contracts/Mocks/ReentrancyToken.sol
  smart-contracts/contracts/Mocks/TrollToken.sol
  smart-contracts/contracts/Mocks/UnicodeToken.sol
  smart-contracts/contracts/Oracle.sol
  smart-contracts/contracts/OracleStorage.sol
  smart-contracts/contracts/Valset.sol
  smart-contracts/contracts/ValsetStorage.sol
  smart-contracts/contracts/interfaces/IBlocklist.sol
  smart-contracts/hardhat.config.ts
  smart-contracts/test/testCosmosBridge.js
  smart-contracts/test/test_bridgeBankLock.js
Labels: Peggy Team

#2594 [ChainOps] API/gRPC updates for sifgen
  cmd/sifgen/main.go
  tools/sifgen/node/node.go
Labels: Ready for Review

#2586 Automatically deploy bridge token for ibc export
  cmd/ebrelayer/relayer/ethereum.go
  cmd/ebrelayer/txs/relayToEthereum.go
  proto/sifnode/oracle/v1/types.proto
  smart-contracts/contracts/CosmosBridge.sol
  smart-contracts/contracts/CosmosBridgeStorage.sol
  smart-contracts/test/helpers/denoms.js
  smart-contracts/test/helpers/testFixture.js
  smart-contracts/test/testCosmosBridge.js
  smart-contracts/test/test_ibcTokenExport.js
  smart-contracts/test/test_txSignatureAggregation.js
  x/ethbridge/keeper/msg_server.go
  x/ethbridge/types/expected_keepers.go
  x/oracle/keeper/keeper.go
  x/oracle/keeper/prophecy.go
  x/oracle/types/events.go
  x/oracle/types/types.pb.go
Labels: Peggy Team

#2599 Inter-Policy Rate Parameter
  proto/sifnode/clp/v1/params.proto
  x/clp/abci.go
  x/clp/genesis.go
  x/clp/keeper/params.go
  x/clp/keeper/pmtp.go
  x/clp/keeper/pmtp_params.go
  x/clp/types/params.pb.go
  x/clp/types/types.go
Labels: PMTP Team

#2602 PMTP - fix first block calc
  x/clp/keeper/pmtp.go
Labels: PMTP Team

#2606 test table generation script
  scripts/pmtp/pmtp-scenarios.py
  scripts/pmtp/pools.json
  scripts/pmtp/scenarios.json
Labels: PMTP Team

#2611 Load testing from ethereum to sifnode
  smart-contracts/src/tsyringe/contracts.ts
  test/load/test_load_tx_ethereum.py
Labels: Peggy Team

#2657 Fix a typo prophcies
  cmd/ebrelayer/relayer/prophecyHandler.go
  proto/sifnode/ethbridge/v1/query.proto
  x/ethbridge/client/cli/query.go
  x/ethbridge/client/rest/rest.go
  x/ethbridge/keeper/grpc_query.go
  x/ethbridge/types/querier.go
  x/ethbridge/types/query.pb.go
Labels: Peggy Team

#2662 Remove a TODO in relayer
  cmd/ebrelayer/relayer/cosmos.go
Labels: Peggy Team

#2655 limit query getProphciesCompleted query result
  cmd/ebrelayer/relayer/prophecyHandler.go
  x/oracle/keeper/prophecy.go
Labels: Peggy Team

#2654 grpc argument
  cmd/ebrelayer/main.go
  cmd/ebrelayer/relayer/cosmos.go
  cmd/ebrelayer/relayer/cosmos_test.go
  cmd/ebrelayer/relayer/ethereum.go
  cmd/ebrelayer/relayer/prophecyHandler.go
Labels: Peggy Team
