Repository Sifchain/sifnode, pull requests merged in 2022-01, with the labels that each got.

#2312 [ChainOps] Sifgen bugfix
  cmd/sifgen/main.go
Labels: Ready for Review

#2302 Just an update for iris.json
  scripts/ibc/tokenregistration/envs/devnet.sh
  scripts/ibc/tokenregistration/sifchain-devnet-1/iris.json
Labels: Sifnode Team

#2309 add new case peggy erc20 token
  smart-contracts/src/tsyringe/contracts.ts
  smart-contracts/test/devenv/test_lockburn_erc20.ts
Labels: Peggy Team

#2303 Fix for multichain network
  .gitignore
  app/setup_handlers.go
  go.mod
  go.sum
  scripts/hermes_config.toml
  scripts/init-multichain.sh
  scripts/run-multichain.sh
  scripts/vote.sh
  version
  x/clp/types/types_test.go
Labels: Sifnode Team

#2341 testnet juno update
  scripts/ibc/tokenregistration/envs/testnet.sh
  scripts/ibc/tokenregistration/sifchain-testnet-1/juno.json
Labels: Sifnode Team

#2350 changes for updated testnet token restry
  scripts/ibc/tokenregistration/envs/testnet.sh
  scripts/ibc/tokenregistration/generate-ibc-jsons.sh
  scripts/ibc/tokenregistration/sifchain-testnet-1/cdmx.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/emoney-eeur.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/emoney.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/likecoin.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/persistence.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/regen.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/scrt.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/sentinel.json
Labels: Sifnode Team

#2351 iris updates for testnet
  scripts/ibc/tokenregistration/envs/testnet.sh
  scripts/ibc/tokenregistration/sifchain-testnet-1/iris.json
Labels: Sifnode Team

#2295 Integ test enable multiple coins
  x/dispensation/handler_test.go
  x/tokenregistry/client/cli/query.go
Labels: Testing Team, Sifnode Team

#2356 updates to tokenregistry
  scripts/ibc/tokenregistration/envs/testnet.sh
  scripts/ibc/tokenregistration/sifchain-testnet-1/osmosis.json
Labels: Sifnode Team

#2336 some scripts and changes that make testing stuck tokens easier
  scripts/change_vote_time.sed
  scripts/client_states.py
  scripts/create_clonable_hermes_channels.sh
  scripts/do_ibc_transfers.sh
  scripts/hermes_config.toml
  scripts/init-multichain.sh
  scripts/rowan-localnet-1-localnet-2.json
  scripts/rowan-localnet-1-localnet-3.json
  scripts/rowan-localnet-2-localnet-1.json
  scripts/rowan-localnet-2-localnet-3.json
  scripts/rowan-localnet-3-localnet-1.json
  scripts/rowan-localnet-3-localnet-2.json
  scripts/run_stuck_token_test.sh
  scripts/vote.sh
  scripts/vote_localnet_1.sh
  scripts/vote_other_chain.sh
  x/ibctransfer/onrecv_packet.go
Labels: Sifnode Team

#2371 just an update for iris on testnet
  scripts/ibc/tokenregistration/envs/testnet.sh
  scripts/ibc/tokenregistration/sifchain-testnet-1/iris.json
Labels: Sifnode Team

#2372 Fixes script that will check ibc client states
  scripts/client_states.py
Labels: Sifnode Team

#2392 new ERC 20 token entries
  scripts/ibc/tokenregistration/sifchain-testnet-1/cbat.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/ceth.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/clink.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/cusdt.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/cwbtc.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/czrx.json
Labels: Sifnode Team

#2393 Fixes decimal precisions or USDT and WBTC and adds IBCIMPORT to all ETH tokens
  scripts/ibc/tokenregistration/sifchain-testnet-1/cbat.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/ceth.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/clink.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/cusdt.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/cwbtc.json
  scripts/ibc/tokenregistration/sifchain-testnet-1/czrx.json
Labels: Sifnode Team

#2400 Task/add erc20s to devnet
  scripts/ibc/tokenregistration/sifchain-devnet-1/cbat.json
  scripts/ibc/tokenregistration/sifchain-devnet-1/ceth.json
  scripts/ibc/tokenregistration/sifchain-devnet-1/clink.json
  scripts/ibc/tokenregistration/sifchain-devnet-1/cusdt.json
  scripts/ibc/tokenregistration/sifchain-devnet-1/cwbtc.json
  scripts/ibc/tokenregistration/sifchain-devnet-1/czrx.json
Labels: Sifnode Team

#2391 Peggy2 docs
  docs/peggy/.gitignore
  docs/peggy/Peggy-Arch.md
  docs/peggy/Peggy-BlockDelay-Arch.md
  docs/peggy/Peggy-Ceth-Account-Set.md
  docs/peggy/Peggy-Export-Data.md
  docs/peggy/Peggy-Flows.md
  docs/peggy/Peggy-Important-Notes.md
  docs/peggy/Peggy-Smart-Contract-Arch.md
  docs/peggy/Peggy-Smart-Contract-Pausing.md
  docs/peggy/RFC/lock_burn_flow/evm_native_burn.dot
  docs/peggy/RFC/lock_burn_flow/evm_native_lock.dot
  docs/peggy/RFC/lock_burn_flow/sif_native_burn.dot
  docs/peggy/RFC/lock_burn_flow/sif_native_lock.dot
  docs/peggy/adr-001-peggy-with-sifnode.md
  docs/peggy/adr-002-ebrelayer-eth-subscribe.md
  docs/peggy/docs/.nojekyll
  docs/peggy/docs/Concepts.md
  docs/peggy/docs/Events.md
  docs/peggy/docs/README.md
  docs/peggy/docs/Scenarios/cosmosExport.md
  docs/peggy/docs/Scenarios/cosmosImport.md
  docs/peggy/docs/Scenarios/doublePegging.md
  docs/peggy/docs/Scenarios/evmExport.md
  docs/peggy/docs/Scenarios/evmImport.md
  docs/peggy/docs/Scenarios/index.md
  docs/peggy/docs/_sidebar.md
  docs/peggy/docs/contracts.md
  docs/peggy/docs/glossary.md
  docs/peggy/docs/index.html
  docs/peggy/images/peggy-flow.png
  docs/peggy/package-lock.json
  docs/peggy/package.json
  smart-contracts/yarn-error.log
Labels: Peggy Team

#2394 fix accounting for TakeOutCustody, TakeInCustody, Borrow
  x/margin/keeper/keeper.go
  x/margin/keeper/keeper_test.go
  x/margin/keeper/msg_server.go
  x/margin/keeper/msg_server_test.go
  x/margin/types/expected_keepers.go
  x/margin/types/types.go
  x/margin/types/types_test.go
Labels: in progress, Margin Team
