Repository Sifchain/sifnode, pull requests merged in 2022-07, with the labels that each got.

#3030 remove used interface file
  smart-contracts/Makefile.artifacts
  smart-contracts/Makefile.smartContracts
  smart-contracts/contracts/interfaces/IBridgeToken.sol
Labels: Peggy Team

#3029 add SPDX-License-Identifier
  smart-contracts/contracts/interfaces/IBlocklist.sol
Labels: Peggy Team

#2984 Check the signature for sign prophecy transaction
  .github/workflows/integrationtest2.yml
  test/integration/execute_integration_tests_peggy2.sh
  test/integration/framework/src/siftool/sifchain.py
  test/integration/src/peggy2/test_peggy2_wrong_signature.py
Labels: Peggy Team

#3022 update cli records-by-name desc
  x/dispensation/client/cli/query.go
Labels: Peggy Team

#3050 Refactor Margin Custody Swap to Use CLP Swap
  x/clp/keeper/swap.go
  x/margin/keeper/keeper.go
  x/margin/keeper/keeper_test.go
  x/margin/keeper/msg_server.go
  x/margin/types/expected_keepers.go
Labels: Ready for Review, Margin Team

#3014 Improve handing of network descriptor validation
  Makefile.protofiles
  cmd/ebrelayer/txs/parser.go
  x/ethbridge/types/msgs.go
Labels: Peggy Team

#3065 Fix Collateral Double Count in Close Repay
  x/margin/keeper/keeper.go
Labels: Margin Team

#3058 update wrong cli desc
  x/dispensation/client/cli/query.go
Labels: Peggy Team

#3019 remove redundant check
  x/dispensation/types/records.go
Labels: Peggy Team

#3011 fix issue 2905, correct error code for metadata check
  x/tokenregistry/types/errors.go
  x/tokenregistry/types/msgs.go
Labels: Peggy Team

#3018 fix error order for dispensation
  x/dispensation/types/errors.go
Labels: Peggy Team

#3010 fix issue 2898, add wrong from account in error
  x/ethbridge/keeper/blacklist.go
  x/ethbridge/keeper/blacklist_test.go
Labels: Peggy Team

#2805 unit test for addExistingBridgeToken
  smart-contracts/test/testBridgeBank.ts
Labels: Peggy Team

#3017 add exponential backoff for ethereum tx receipt querying
  cmd/ebrelayer/txs/relayToEthereum.go
Labels: Peggy Team

#3007 Add the genesis check for ethbridge module
  x/ethbridge/genesis.go
  x/ethbridge/genesis_test.go
Labels: Peggy Team
